// Centralized adoption URL registry — all 222 active dogs
// Generated: 2026-08-05T22:25:11.844Z

import type { AdoptionUrlStatus, AdoptionUrlSource } from "./adoptionUrlSchema";

type RegistryEntry = {
  adoptionProfileUrl: string | null;
  status: AdoptionUrlStatus;
  source: AdoptionUrlSource;
  verifiedAt: string | null;
  notes: string;
};


const org_21648834_data: Record<string, RegistryEntry> = {
  "21648834": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22082320": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22171117": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22239467": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22314073": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22314077": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22392666": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22432212": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22432215": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22432216": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22442828": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22456869": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22459462": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22467954": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22467959": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22482405": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22501221": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22511514": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22601625": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22611930": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22614989": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22615470": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22615472": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22617888": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22617889": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22617890": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22617891": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22617894": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
  "22648974": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "No Time to Spare Animal Rescue and Sanctuary — not yet resolved",
  },
};

const org_12030390_data: Record<string, RegistryEntry> = {
  "12030390": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "13530849": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "13530902": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "15650615": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "15822193": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "15882590": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "16580406": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "16945129": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "16945630": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "17000697": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "17595597": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "17979761": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "18079852": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "18433049": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "18638156": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "18740690": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "18888148": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "18894509": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "18894528": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "19013492": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "19122463": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "19129573": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "19189338": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "19273795": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
  "19273801": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "STRAY PAWS RESCUE — not yet resolved",
  },
};

const org_10819783_data: Record<string, RegistryEntry> = {
  "10819783": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "10819835": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "12409136": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "12409137": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "12409144": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "12409165": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "14920124": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "16073269": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "16073285": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "16073288": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "18929496": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "20835488": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "20835496": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "20835507": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "20835549": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "20835550": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "20917702": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "20917717": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "21472713": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "21722101": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "22332899": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "22332968": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "22484739": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
  "22484750": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Hope Animal Rescues — not yet resolved",
  },
};

const org_22308787_data: Record<string, RegistryEntry> = {
  "22308787": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22354590": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22413348": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22413349": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22444996": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22444997": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22478468": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22516077": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22517357": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22524213": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22535577": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22547385": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22564997": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22564998": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22591664": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22609343": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22610008": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22613100": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22644434": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
  "22646847": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St Charles County Humane Services — not yet resolved",
  },
};

// SPENCER PET RESCUE — All 17 dogs, verified GetBuddy URLs
const org_22649636_data: Record<string, RegistryEntry> = {
  // Carl — VERIFIED GetBuddy
  "22649636": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/69d826adfa9cfc803fef5b57",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Carl, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Darla — VERIFIED GetBuddy
  "22649637": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/681dc67a5ab6746988e790b2",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:30:00Z",
    notes: "Verified GetBuddy: Darla, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Dart — VERIFIED GetBuddy
  "22649640": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/69f51f3c739af4ed5a06b83d",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:30:00Z",
    notes: "Verified GetBuddy: Dart (from Stranger Things), Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Dumpling — VERIFIED GetBuddy
  "22649644": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/6a39956de87cf5014cec6074",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:30:00Z",
    notes: "Verified GetBuddy: Dumpling, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Holden aka Harlan — VERIFIED GetBuddy
  "22649646": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/69f51c1d52a11dda4fa10eea",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Holden aka Harlan, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Jid aka Jeddy Bear — VERIFIED GetBuddy
  "22649648": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/69f5234b739af4ed5a06b845",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Jid aka Jeddy Bear, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Lemon — VERIFIED GetBuddy
  "22649650": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/6a399409e87cf5014cec6072",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Lemon, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Linus — VERIFIED GetBuddy
  "22649652": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/699eae26e7817824d5874a7d",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:30:00Z",
    notes: "Verified GetBuddy: Linus, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Macho Man — VERIFIED GetBuddy
  "22649657": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/6a54f7c42f22adcfaaa0e238",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:30:00Z",
    notes: "Verified GetBuddy: Macho Man, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Macy — VERIFIED GetBuddy
  "22649660": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/681dc6795ab6746988e790ab",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Macy (listed as Yasmin on GetBuddy), Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Paco — VERIFIED GetBuddy (original)
  "22649663": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/699d5d19e7817824d57fc1de",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T00:00:00Z",
    notes: "Verified GetBuddy: Paco, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Raisin — VERIFIED GetBuddy
  "22649666": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/6a186b5f1ee9d8b1b7dc14b5",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Raisin, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Raya — VERIFIED GetBuddy
  "22649668": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/69d82a6ffa9cfc803fef5b5e",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Raya (listed as Nino on GetBuddy), Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Sweetie — VERIFIED GetBuddy
  "22649671": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/6a54f92f2f22adcfaaa0e23b",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Sweetie, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Tango — VERIFIED GetBuddy
  "22649675": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/68e779edd634356c103f77c6",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Tango, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Tiramisu — VERIFIED GetBuddy
  "22649678": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/6a398d71e87cf5014cec606d",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Tiramisu, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
  // Vida — VERIFIED GetBuddy
  "22649681": {
    adoptionProfileUrl: "https://www.getbuddy.com/pet/681dc6795ab6746988e790ab",
    status: "verified-direct-dog-page",
    source: "getbuddy",
    verifiedAt: "2026-08-05T23:35:00Z",
    notes: "Verified GetBuddy: Vida, Spencer Pet Rescue, O Fallon IL, adoptable",
  },
};

const org_19547584_data: Record<string, RegistryEntry> = {
  "19547584": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "20694980": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "20994771": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "21180799": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "21252905": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "21266577": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "21287790": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "21337805": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "21486004": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "21502723": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "21571542": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "21630520": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "21902603": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "22510085": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
  "22642998": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Come Bye Border Collie Rescue — not yet resolved",
  },
};

const org_22452271_data: Record<string, RegistryEntry> = {
  "22452271": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22592570": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22603856": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22625928": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22627276": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22627788": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22635061": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22648267": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22648268": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22648270": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22652967": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22653554": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
  "22655180": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Animal Protective Association of Missouri — not yet resolved",
  },
};

const org_21937865_data: Record<string, RegistryEntry> = {
  "21937865": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22058366": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22157865": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22157923": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22168640": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22168643": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22316183": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22316200": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22316206": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22455998": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22456007": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22549624": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
  "22549641": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Perry County Humane Society of Illinois — not yet resolved",
  },
};

const org_21881216_data: Record<string, RegistryEntry> = {
  "21881216": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22259414": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22273763": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22352140": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22400599": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22475460": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22499881": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22502140": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22502142": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22502143": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22540950": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
  "22608191": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Clair County Animal Adoption Center — not yet resolved",
  },
};

const org_19621150_data: Record<string, RegistryEntry> = {
  "19621150": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "4 Paws 4 Rescue — not yet resolved",
  },
  "21059265": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "4 Paws 4 Rescue — not yet resolved",
  },
  "22301228": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "4 Paws 4 Rescue — not yet resolved",
  },
  "22393127": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "4 Paws 4 Rescue — not yet resolved",
  },
  "22575675": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "4 Paws 4 Rescue — not yet resolved",
  },
  "22600790": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "4 Paws 4 Rescue — not yet resolved",
  },
  "22613272": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "4 Paws 4 Rescue — not yet resolved",
  },
  "22625903": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "4 Paws 4 Rescue — not yet resolved",
  },
  "22644008": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "4 Paws 4 Rescue — not yet resolved",
  },
  "22644009": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "4 Paws 4 Rescue — not yet resolved",
  },
};

const org_22446476_data: Record<string, RegistryEntry> = {
  "22446476": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Humane Society of Missouri — not yet resolved",
  },
  "22596961": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Humane Society of Missouri — not yet resolved",
  },
  "22603038": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Humane Society of Missouri — not yet resolved",
  },
  "22612510": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Humane Society of Missouri — not yet resolved",
  },
  "22618640": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Humane Society of Missouri — not yet resolved",
  },
  "22619717": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Humane Society of Missouri — not yet resolved",
  },
  "22635714": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Humane Society of Missouri — not yet resolved",
  },
  "22647968": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Humane Society of Missouri — not yet resolved",
  },
  "22649599": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Humane Society of Missouri — not yet resolved",
  },
};

const org_22174123_data: Record<string, RegistryEntry> = {
  "22174123": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Country Acres Rescue — not yet resolved",
  },
  "22194571": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Country Acres Rescue — not yet resolved",
  },
  "22194580": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Country Acres Rescue — not yet resolved",
  },
  "22225221": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Country Acres Rescue — not yet resolved",
  },
  "22225231": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Country Acres Rescue — not yet resolved",
  },
  "22296359": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Country Acres Rescue — not yet resolved",
  },
};

const org_22223788_data: Record<string, RegistryEntry> = {
  "22223788": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Advocates 4 Animals Pet Food Pantry — not yet resolved",
  },
  "22432764": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Advocates 4 Animals Pet Food Pantry — not yet resolved",
  },
  "22439370": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Advocates 4 Animals Pet Food Pantry — not yet resolved",
  },
  "22596462": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Advocates 4 Animals Pet Food Pantry — not yet resolved",
  },
  "22633439": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Advocates 4 Animals Pet Food Pantry — not yet resolved",
  },
  "22641970": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Advocates 4 Animals Pet Food Pantry — not yet resolved",
  },
};

const org_20515053_data: Record<string, RegistryEntry> = {
  "20515053": {
    adoptionProfileUrl: null,
    status: "dead-or-removed",
    source: "unknown",
    verifiedAt: "2026-08-04T00:00:00Z",
    notes: "Mastino Rescue: Wix site serves empty animal profiles (verified 2026-08-04)",
  },
  "20583459": {
    adoptionProfileUrl: null,
    status: "dead-or-removed",
    source: "unknown",
    verifiedAt: "2026-08-04T00:00:00Z",
    notes: "Mastino Rescue: Wix site serves empty animal profiles (verified 2026-08-04)",
  },
  "20765333": {
    adoptionProfileUrl: null,
    status: "dead-or-removed",
    source: "unknown",
    verifiedAt: "2026-08-04T00:00:00Z",
    notes: "Mastino Rescue: Wix site serves empty animal profiles (verified 2026-08-04)",
  },
  "20984062": {
    adoptionProfileUrl: null,
    status: "dead-or-removed",
    source: "unknown",
    verifiedAt: "2026-08-04T00:00:00Z",
    notes: "Mastino Rescue: Wix site serves empty animal profiles (verified 2026-08-04)",
  },
  "21940794": {
    adoptionProfileUrl: null,
    status: "dead-or-removed",
    source: "unknown",
    verifiedAt: "2026-08-04T00:00:00Z",
    notes: "Mastino Rescue: Wix site serves empty animal profiles (verified 2026-08-04)",
  },
  "22207544": {
    adoptionProfileUrl: null,
    status: "dead-or-removed",
    source: "unknown",
    verifiedAt: "2026-08-04T00:00:00Z",
    notes: "Mastino Rescue: Wix site serves empty animal profiles (verified 2026-08-04)",
  },
};

const org_17536864_data: Record<string, RegistryEntry> = {
  "17536864": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Animal Pet Adoptions — not yet resolved",
  },
  "17819052": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Animal Pet Adoptions — not yet resolved",
  },
  "21070243": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Animal Pet Adoptions — not yet resolved",
  },
  "21968587": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "St. Animal Pet Adoptions — not yet resolved",
  },
};

const org_21711327_data: Record<string, RegistryEntry> = {
  "21711327": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Needy Paws Rescue — not yet resolved",
  },
  "22557755": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Needy Paws Rescue — not yet resolved",
  },
  "22570829": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Needy Paws Rescue — not yet resolved",
  },
  "22580255": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Needy Paws Rescue — not yet resolved",
  },
};

const org_22106499_data: Record<string, RegistryEntry> = {
  "22106499": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Midwest Doberman Rescue of St. Louis — not yet resolved",
  },
  "22595613": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Midwest Doberman Rescue of St. Louis — not yet resolved",
  },
  "22616903": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Midwest Doberman Rescue of St. Louis — not yet resolved",
  },
};

const org_21151373_data: Record<string, RegistryEntry> = {
  "21151373": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Piedmont Pound Paws, Inc. — not yet resolved",
  },
  "21151381": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Piedmont Pound Paws, Inc. — not yet resolved",
  },
  "21151398": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Piedmont Pound Paws, Inc. — not yet resolved",
  },
};

const org_12645754_data: Record<string, RegistryEntry> = {
  "12645754": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Camp Chaos Puppy Rescue — not yet resolved",
  },
  "22135559": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "Camp Chaos Puppy Rescue — not yet resolved",
  },
};

const org_22606131_data: Record<string, RegistryEntry> = {
  "22606131": {
    adoptionProfileUrl: null,
    status: "unverified",
    source: "unknown",
    verifiedAt: null,
    notes: "All Paws Rescue, Inc. — not yet resolved",
  },
};

export const adoptionUrlRegistry: Record<string, RegistryEntry> = {
  ...org_21648834_data,
  ...org_12030390_data,
  ...org_10819783_data,
  ...org_22308787_data,
  ...org_22649636_data,
  ...org_19547584_data,
  ...org_22452271_data,
  ...org_21937865_data,
  ...org_21881216_data,
  ...org_19621150_data,
  ...org_22446476_data,
  ...org_22174123_data,
  ...org_22223788_data,
  ...org_20515053_data,
  ...org_17536864_data,
  ...org_21711327_data,
  ...org_22106499_data,
  ...org_21151373_data,
  ...org_12645754_data,
  ...org_22606131_data,
};

export function getAdoptionUrlStatus(animalId: string): RegistryEntry | null {
  return adoptionUrlRegistry[animalId] ?? null;
}

export function hasVerifiedAdoptionProfile(animalId: string): boolean {
  const entry = adoptionUrlRegistry[animalId];
  return entry?.status === "verified-direct-dog-page" && entry?.adoptionProfileUrl !== null;
}

export function getVerifiedAdoptionUrl(animalId: string): string | null {
  const entry = adoptionUrlRegistry[animalId];
  if (entry?.status === "verified-direct-dog-page") {
    return entry.adoptionProfileUrl;
  }
  return null;
}
