// Structured dog profiles — the permanent, owner-curated dog pages.
// A profile is ONE data record; the page renders itself from it. Adding a
// future dog = add a record here + drop images in /public. Slugs must never
// be all digits — numeric /dogs/[id] paths belong to live rescue listings.
//
// A profile carries the dog's LOCKED seven-card deck: exactly seven
// nicknames, owner-curated, in owner order, hero card first. The page shows
// ONE card at a time — the full seven never render anywhere.
//
// Truth rule: verifiedFacts are the only place for real-world claims, and
// every fact names its source (owner / rescue). Nicknames and sayings may
// only riff on what the owner actually supplied — findUnverifiedClaims
// enforces that boundary and the test suite runs it on every profile.

import { DECK_SIZE, findDeckProblems, type CardPair } from "./cards/tradingCards";
import type { PhotoSpec } from "./cards/photoFraming";

export type ProfileFact = { label: string; source: "owner" | "rescue" };

export type DogProfileV1 = {
  version: 1;
  slug: string;
  realName: string;
  /** the name on the hero card — cards[0].nickname, always first */
  featuredNickname: string;
  /** the locked seven, in spin order; owner-curated, never generated */
  cards: CardPair[];
  profileType: "family" | "adoptable";
  adoptionStatus: "home" | "adoptable";
  primaryImage: string;
  primaryImageAlt: string;
  /** manual framing for the card photo window; omitted = Fit Whole Dog */
  photoSpec?: PhotoSpec;
  intro: string[];
  verifiedFacts: ProfileFact[];
  shelter?: { name: string; url?: string };
  location?: string;
  adoptionUrl?: string;
  shareText: string;
  seoTitle: string;
  seoDescription: string;
  theme: { accent: string };
};

// Phrases that must never appear anywhere public on a profile. Plain card
// language only — nothing that sounds like machinery.
export const BANNED_PUBLIC_PHRASES = [
  "ai-powered",
  "generated by ai",
  "generated",
  "engine",
  "algorithm",
  "intelligen",
  "identity system",
  "personality analysis",
  "infinite names",
  "imagination engine",
  "creative engine",
  "powered by technology",
  "create with ai",
];

// Real-world claim terms that only a shelter, foster, rescuer, or the owner
// can supply — and then only inside verifiedFacts, never as a joke.
export const CLAIM_TERMS = [
  "good with kids",
  "good with cats",
  "good with dogs",
  "housetrained",
  "house trained",
  "potty trained",
  "vaccinated",
  "neutered",
  "spayed",
  "microchip",
  "bite",
  "aggressive",
  "medical",
  "diagnos",
  "medication",
  "obedience",
  "crate trained",
];

// Historical misspellings of family names that must never reappear.
// NOTE (owner correction, Jul 30 2026): "Bruce Zayne" IS a locked card —
// Bruce Wayne wordplay, card three of Isaiah's seven — so it is no longer
// banned. Only the true mistakes stay on this list.
export const BANNED_HERO_SPELLINGS = ["bruze zayne", "bruiser"];

function humorStrings(p: DogProfileV1): string[] {
  return [
    ...p.intro,
    ...p.cards.flatMap((c) => [c.nickname, ...c.sayings]),
    p.shareText,
    p.seoTitle,
    p.seoDescription,
  ];
}

// Returns every humor string that smuggles in a real-world claim. Must be
// empty for every shipped profile.
export function findUnverifiedClaims(p: DogProfileV1): string[] {
  return humorStrings(p).filter((s) => {
    const low = s.toLowerCase();
    return CLAIM_TERMS.some((term) => low.includes(term));
  });
}

// Returns every profile string containing a banned public phrase.
export function findBannedPublicPhrases(p: DogProfileV1): string[] {
  const all = JSON.stringify(p).toLowerCase();
  return BANNED_PUBLIC_PHRASES.filter((phrase) => all.includes(phrase));
}

export function findBannedHeroSpellings(p: DogProfileV1): string[] {
  const all = JSON.stringify(p).toLowerCase();
  return BANNED_HERO_SPELLINGS.filter((s) => all.includes(s));
}

// Deck problems for a profile — locked decks skip the name-connection rule
// (a human made each name personal) but never the count/dupe/filler rules.
export function findProfileDeckProblems(p: DogProfileV1): string[] {
  const problems = findDeckProblems(p.cards, { realName: p.realName, locked: true });
  if (p.cards.length !== DECK_SIZE) return problems; // count problem already reported
  if (p.cards[0].nickname !== p.featuredNickname) {
    problems.push(`hero card is ${p.cards[0].nickname}, expected ${p.featuredNickname}`);
  }
  return problems;
}

// Isaiah — DJ's family dog, public by owner decision (Jul 2026). The
// permanent example: his LOCKED seven, exact spelling and order, set by the
// owner on Jul 30 2026. Batdog is the permanent hero card and always opens
// the deck. Never add, replace, rewrite, autocorrect, reorder, or generate
// alternatives for these seven names.
const isaiah: DogProfileV1 = {
  version: 1,
  slug: "isaiah",
  realName: "Isaiah",
  featuredNickname: "Batdog",
  cards: [
    { nickname: "Batdog", sayings: ["Saving the neighborhood after nap time.", "No one has ever seen Isaiah and Batdog in the same room."] },
    { nickname: "The Dark Zay", sayings: ["Quiet all day. Legendary after dinner.", "The hero this living room deserves."] },
    { nickname: "Bruce Zayne", sayings: ["Respectable daytime identity. Suspiciously calm.", "Definitely not Batdog. Stop asking."] },
    { nickname: "Darth Zayder", sayings: ["The bark side is strong with this one.", "Appears after dinner. Ask the couch."] },
    { nickname: "Isaiah Papaya", sayings: ["It rhymes. That's the whole case.", "Sweet, seedless, occasionally slippery."] },
    { nickname: "Izzy Osbourne", sayings: ["Loud. Legendary. Slightly unhinged.", "Rocks the entire cul-de-sac."] },
    { nickname: "Zayaplaya", sayings: ["Too smooth for the leash.", "It's not a phase. It's a lifestyle."] },
  ],
  profileType: "family",
  adoptionStatus: "home",
  primaryImage: "/isaiah.jpg",
  primaryImageAlt: "Isaiah, a black-and-white dog, sitting very still and looking directly at the camera",
  // Owner-tuned framing: keeps the full head, both ears, and the front paws
  // in the 4:5 window (photo is 805×1038; focus near the top of the frame).
  photoSpec: { fit: "focal", x: 0.5, y: 0.12, zoom: 1 },
  intro: [
    "Family dog by day. Batdog after dinner.",
    "Real, rescued, and extremely not for adoption.",
  ],
  verifiedFacts: [
    { label: "Real name: Isaiah — it's on the tag", source: "owner" },
    { label: "Family dog, already home", source: "owner" },
    { label: "Adopted from Home 2 Home Canine Orphanage", source: "owner" },
    { label: "St. Louis area", source: "owner" },
    { label: "Black and white coat", source: "owner" },
  ],
  shelter: { name: "Home 2 Home Canine Orphanage", url: "https://home2homecanineorphanage.org/adopt" },
  location: "St. Louis area",
  shareText:
    "Meet Isaiah — a.k.a. Batdog. One very good boy, one trading card at a time. He already has a home; lots of dogs near you still need one.",
  seoTitle: "Isaiah — Batdog · Fun Dog Trading Cards",
  seoDescription:
    "Isaiah: family dog, featured card Batdog. Spin a new card, share today's, then meet a dog near you who still needs a home.",
  theme: { accent: "#2DD4BF" },
};

const PROFILES: Record<string, DogProfileV1> = {
  [isaiah.slug]: isaiah,
};

export function getDogProfile(slug: string): DogProfileV1 | null {
  // All-digit paths are live rescue listings, never local profiles.
  if (/^\d+$/.test(slug)) return null;
  return PROFILES[slug.toLowerCase()] ?? null;
}

export function listDogProfiles(): DogProfileV1[] {
  return Object.values(PROFILES);
}
