// Structured dog profiles — the permanent, owner-curated dog pages.
// A profile is ONE data record; the page renders itself from it. Adding a
// future dog = add a record here + drop images in /public. Slugs must never
// be all digits — numeric /dogs/[id] paths belong to live rescue listings.
//
// Truth rule: verifiedFacts are the only place for real-world claims, and
// every fact names its source (owner / rescue). Humor fields may only riff
// on the names and facts the owner actually provided — findUnverifiedClaims
// enforces that boundary and the test suite runs it on every profile.

import {
  BANNED_HERO_SPELLINGS,
  ISAIAH_HERO_ID,
  ISAIAH_HERO_NAME,
  ISAIAH_SUBTITLE,
  type HeroIdentity,
} from "./identity/heroIdentity";

export type ProfileFact = { label: string; source: "owner" | "rescue" };
export type NicknameGroup = { title: string; names: string[] };
export type SituationalName = { when: string; name: string };
export type CharacterCard = { name: string; tagline: string };
export type ProfileSection = { title: string; lines: string[] };

export type DogProfileV1 = {
  version: 1;
  slug: string;
  realName: string;
  displayTitle: string;
  /** the current chosen hero identity's name (e.g. "Bruzer Zayne");
   *  displayTitle then reads as the legend subtitle */
  heroName?: string;
  defaultHeroId?: string;
  /** the chooser's deck: curated + behavior + mood identities */
  heroIdentities?: HeroIdentity[];
  profileType: "family" | "adoptable";
  adoptionStatus: "home" | "adoptable";
  primaryImage: string;
  primaryImageAlt: string;
  gallery: string[];
  intro: string[];
  verifiedFacts: ProfileFact[];
  aliases: string[];
  nicknameGroups: NicknameGroup[];
  situationalNames: SituationalName[];
  characterCards: CharacterCard[];
  // Owner-supplied only. Empty = the section simply doesn't render.
  personalityNotes: string[];
  realQuirks: string[];
  likes: string[];
  dislikes: string[];
  abilities: string[];
  weaknesses: string[];
  funnyCharges: string[];
  quotes: string[];
  sections: ProfileSection[];
  shelter?: { name: string; url?: string };
  location?: string;
  adoptionUrl?: string;
  shareText: string;
  seoTitle: string;
  seoDescription: string;
  theme: { accent: string };
};

// Phrases that must never appear anywhere public on a profile.
export const BANNED_PUBLIC_PHRASES = [
  "ai-powered",
  "generated by ai",
  "imagination engine",
  "creative engine",
  "intelligent profile",
  "powered by technology",
  "create with ai",
];

// Real-world claim terms that only a shelter, foster, rescuer, or the owner
// can supply — and then only inside verifiedFacts, never as a joke.
const CLAIM_TERMS = [
  "good with kids",
  "good with cats",
  "good with dogs",
  "housetrained",
  "house trained",
  "potty trained",
  "vaccinated",
  "neutered",
  "spayed",
  "microchip",
  "bite",
  "aggressive",
  "medical",
  "diagnos",
  "medication",
  "obedience",
  "crate trained",
];

function humorStrings(p: DogProfileV1): string[] {
  return [
    ...p.intro,
    ...p.aliases,
    ...(p.heroIdentities ?? []).flatMap((h) => [h.name, h.subtitle ?? "", h.tagline ?? ""]),
    ...p.nicknameGroups.flatMap((g) => [g.title, ...g.names]),
    ...p.situationalNames.flatMap((s) => [s.when, s.name]),
    ...p.characterCards.flatMap((c) => [c.name, c.tagline]),
    ...p.funnyCharges,
    ...p.quotes,
    ...p.sections.flatMap((s) => [s.title, ...s.lines]),
    p.shareText,
    p.seoTitle,
    p.seoDescription,
  ];
}

// Returns every humor string that smuggles in a real-world claim. Must be
// empty for every shipped profile.
export function findUnverifiedClaims(p: DogProfileV1): string[] {
  return humorStrings(p).filter((s) => {
    const low = s.toLowerCase();
    return CLAIM_TERMS.some((term) => low.includes(term));
  });
}

// Returns every profile string containing a banned public phrase.
export function findBannedPublicPhrases(p: DogProfileV1): string[] {
  const all = JSON.stringify(p).toLowerCase();
  return BANNED_PUBLIC_PHRASES.filter((phrase) => all.includes(phrase));
}

// The canonical hero spelling is "Bruzer Zayne" — the historical
// misspellings must never reappear anywhere in any profile.
export function findBannedHeroSpellings(p: DogProfileV1): string[] {
  const all = JSON.stringify(p).toLowerCase();
  return BANNED_HERO_SPELLINGS.filter((s) => all.includes(s));
}

const isaiah: DogProfileV1 = {
  version: 1,
  slug: "isaiah",
  realName: "Isaiah",
  // Canonical hero identity (owner-corrected): BRUZER ZAYNE, subtitle
  // "The Dark Zay", known in ordinary life as Isaiah.
  displayTitle: ISAIAH_SUBTITLE,
  heroName: ISAIAH_HERO_NAME,
  defaultHeroId: ISAIAH_HERO_ID,
  heroIdentities: [
    { id: ISAIAH_HERO_ID, name: ISAIAH_HERO_NAME, subtitle: ISAIAH_SUBTITLE, tagline: "The flagship. The legend. The reason you're here.", kind: "curated" },
    { id: "batdog", name: "Batdog", subtitle: "The hero this living room deserves", tagline: "No one has ever seen Isaiah and Batdog in the same room.", kind: "curated" },
    { id: "the-dark-zayne", name: "The Dark Zayne", subtitle: "Formal occasions", tagline: "Same dog, longer cape.", kind: "curated" },
    { id: "darthzayder", name: "DarthZayder", subtitle: "After dinner", tagline: "Appears after dinner. Ask the couch.", kind: "behavior" },
    { id: "spiderzay", name: "SpiderZay", subtitle: "Your friendly neighborhood Zay", tagline: "Climbs nothing. Claims everything.", kind: "curated" },
    { id: "superzay", name: "SuperZay", subtitle: "Mild-mannered Isaiah is the disguise", tagline: "Faster than a dropped meatball.", kind: "curated" },
    { id: "zenzaya", name: "ZenZaya", subtitle: "Nap time", tagline: "Inner peace. Outer sprawl.", kind: "mood" },
    { id: "zay-train", name: "Zay Train", subtitle: "Zoomies o'clock", tagline: "All aboard. No brakes.", kind: "mood" },
    { id: "isaiah-papaya", name: "Isaiah Papaya", subtitle: "The rhyme department", tagline: "It rhymes. That's the whole case.", kind: "recent" },
  ],
  profileType: "family",
  adoptionStatus: "home",
  primaryImage: "/isaiah.jpg",
  primaryImageAlt: "Isaiah, a black-and-white dog, sitting very still and looking directly at the camera",
  gallery: ["/isaiah.jpg"],
  intro: [
    "Family dog by day. Something a little more dramatic after dinner.",
    "Real, rescued, and extremely not for adoption.",
  ],
  verifiedFacts: [
    { label: "Real name: Isaiah — it's on the tag", source: "owner" },
    { label: "Family dog, already home", source: "owner" },
    { label: "Adopted from Home 2 Home Canine Orphanage", source: "owner" },
    { label: "St. Louis area", source: "owner" },
    { label: "Black and white coat", source: "owner" },
    { label: "Known aliases: 18", source: "owner" },
  ],
  aliases: [
    "Isaiah",
    "Zay",
    "Zay-Zay",
    "Big Zay",
    "Batdog",
    "Bruzer Zayne",
    "The Dark Zay",
    "The Dark Zayne",
    "Isaiah Papaya",
    "Zay Day",
    "Zaynomore",
    "ZenZaya",
    "SpiderZay",
    "SuperZay",
    "DarthZayder",
    "Dizzy Izzy",
    "Izzy Smalls",
    "Zay Train",
  ],
  nicknameGroups: [
    {
      title: "Everyday rotation",
      names: ["Zay", "Zay-Zay", "Big Zay", "Zay Day", "Zay Train"],
    },
    {
      title: "Rhyme department",
      names: ["Isaiah Papaya", "Dizzy Izzy", "Izzy Smalls", "ZenZaya", "Zaynomore"],
    },
  ],
  situationalNames: [
    { when: "By day", name: "Bruzer Zayne" },
    { when: "After dinner", name: "DarthZayder" },
    { when: "Nap time", name: "ZenZaya" },
    { when: "Formal occasions", name: "The Dark Zayne" },
    { when: "Full-name serious", name: "Isaiah" },
  ],
  characterCards: [
    { name: "Batdog", tagline: "The hero this living room deserves." },
    { name: "Bruzer Zayne", tagline: "Respectable daytime identity. Suspiciously calm." },
    { name: "The Dark Zay", tagline: "The flagship. The legend. The reason you're here." },
    { name: "The Dark Zayne", tagline: "Same dog, longer cape." },
    { name: "DarthZayder", tagline: "Appears after dinner. Ask the couch." },
    { name: "SpiderZay", tagline: "Your friendly neighborhood Zay." },
    { name: "SuperZay", tagline: "Mild-mannered Isaiah is the disguise." },
  ],
  // OWNER: real facts only, in DJ's words. Empty sections stay hidden.
  personalityNotes: [],
  realQuirks: [],
  likes: [],
  dislikes: [],
  abilities: [],
  weaknesses: [],
  funnyCharges: [
    "Operating under 18 known aliases",
    "Impersonating at least four superheroes and one Sith lord",
    "Refusing to confirm or deny being Batdog",
    "Verdict: too good a boy. Case dismissed.",
  ],
  quotes: [
    "Not all heroes wear capes. Some wear a blue bone tag.",
    "By day: Isaiah. After dinner: DarthZayder.",
    "18 aliases. Zero regrets.",
    "Isaiah already has a home. His aliases are everywhere.",
  ],
  sections: [
    {
      title: "The Origin of the Dark Zay",
      lines: [
        "Every legend starts somewhere. This one starts at Home 2 Home Canine Orphanage, near St. Louis.",
        "A family walked in. A dog walked out with 18 names.",
        "No radioactive anything. Just adoption.",
      ],
    },
    {
      title: "Evidence Collected",
      lines: [
        "Exhibit A: the tag clearly says ISAIAH. The eyes say Bruzer Zayne.",
        "Exhibit B: no one has ever seen Isaiah and Batdog in the same room.",
      ],
    },
  ],
  shelter: { name: "Home 2 Home Canine Orphanage", url: "https://home2homecanineorphanage.org/adopt" },
  location: "St. Louis area",
  shareText:
    "Meet Isaiah — a.k.a. Bruzer Zayne, The Dark Zay. 18 aliases, one very good boy. He already has a home; lots of dogs near you still need one.",
  seoTitle: "Bruzer Zayne — The Dark Zay",
  seoDescription:
    "Isaiah: family dog, 18 known aliases, zero available for adoption. Meet Bruzer Zayne, The Dark Zay — then meet a dog who still needs a home.",
  theme: { accent: "#2DD4BF" },
};

const PROFILES: Record<string, DogProfileV1> = {
  [isaiah.slug]: isaiah,
};

export function getDogProfile(slug: string): DogProfileV1 | null {
  // All-digit paths are live rescue listings, never local profiles.
  if (/^\d+$/.test(slug)) return null;
  return PROFILES[slug.toLowerCase()] ?? null;
}

export function listDogProfiles(): DogProfileV1[] {
  return Object.values(PROFILES);
}
