// Structured dog profiles — the permanent, owner-curated dog pages.
// A profile is ONE data record; the page renders itself from it. Adding a
// future dog = add a record here + drop images in /public. Slugs must never
// be all digits — numeric /dogs/[id] paths belong to live rescue listings.
//
// A profile is now a trading-card deck: a small set of nicknames worth
// keeping, each with the sayings that fit it. The page shows ONE card at a
// time — the full list never renders anywhere.
//
// Truth rule: verifiedFacts are the only place for real-world claims, and
// every fact names its source (owner / rescue). Nicknames and sayings may
// only riff on what the owner actually supplied — findUnverifiedClaims
// enforces that boundary and the test suite runs it on every profile.

import type { CardPair } from "./cards/tradingCards";

export type ProfileFact = { label: string; source: "owner" | "rescue" };

export type DogProfileV1 = {
  version: 1;
  slug: string;
  realName: string;
  /** the name on the first card — cards[0].nickname */
  featuredNickname: string;
  /** the spin deck, in spin order; owner-curated, kept short */
  cards: CardPair[];
  profileType: "family" | "adoptable";
  adoptionStatus: "home" | "adoptable";
  primaryImage: string;
  primaryImageAlt: string;
  intro: string[];
  verifiedFacts: ProfileFact[];
  shelter?: { name: string; url?: string };
  location?: string;
  adoptionUrl?: string;
  shareText: string;
  seoTitle: string;
  seoDescription: string;
  theme: { accent: string };
};

// Phrases that must never appear anywhere public on a profile. Plain card
// language only — nothing that sounds like machinery.
export const BANNED_PUBLIC_PHRASES = [
  "ai-powered",
  "generated by ai",
  "generated",
  "engine",
  "algorithm",
  "intelligen",
  "identity system",
  "personality analysis",
  "infinite names",
  "imagination engine",
  "creative engine",
  "powered by technology",
  "create with ai",
];

// Real-world claim terms that only a shelter, foster, rescuer, or the owner
// can supply — and then only inside verifiedFacts, never as a joke.
export const CLAIM_TERMS = [
  "good with kids",
  "good with cats",
  "good with dogs",
  "housetrained",
  "house trained",
  "potty trained",
  "vaccinated",
  "neutered",
  "spayed",
  "microchip",
  "bite",
  "aggressive",
  "medical",
  "diagnos",
  "medication",
  "obedience",
  "crate trained",
];

// The canonical family spelling is "Bruzer Zayne" — the historical
// misspellings must never reappear anywhere in any profile.
export const BANNED_HERO_SPELLINGS = ["bruce zayne", "bruze zayne", "bruiser"];

function humorStrings(p: DogProfileV1): string[] {
  return [
    ...p.intro,
    ...p.cards.flatMap((c) => [c.nickname, ...c.sayings]),
    p.shareText,
    p.seoTitle,
    p.seoDescription,
  ];
}

// Returns every humor string that smuggles in a real-world claim. Must be
// empty for every shipped profile.
export function findUnverifiedClaims(p: DogProfileV1): string[] {
  return humorStrings(p).filter((s) => {
    const low = s.toLowerCase();
    return CLAIM_TERMS.some((term) => low.includes(term));
  });
}

// Returns every profile string containing a banned public phrase.
export function findBannedPublicPhrases(p: DogProfileV1): string[] {
  const all = JSON.stringify(p).toLowerCase();
  return BANNED_PUBLIC_PHRASES.filter((phrase) => all.includes(phrase));
}

export function findBannedHeroSpellings(p: DogProfileV1): string[] {
  const all = JSON.stringify(p).toLowerCase();
  return BANNED_HERO_SPELLINGS.filter((s) => all.includes(s));
}

// Isaiah — DJ's family dog, public by owner decision (Jul 2026). Featured
// card: BATDOG. Every nickname below is one the family could actually keep
// calling him; the deck stays short on purpose.
const isaiah: DogProfileV1 = {
  version: 1,
  slug: "isaiah",
  realName: "Isaiah",
  featuredNickname: "Batdog",
  cards: [
    { nickname: "Batdog", sayings: ["Saving the neighborhood after nap time.", "No one has ever seen Isaiah and Batdog in the same room."] },
    { nickname: "Big Zay", sayings: ["Adopted the family. Kept the couch.", "The floor is mine. All of it."] },
    { nickname: "Isaiah Jones", sayings: ["Local legend. Ask anyone.", "Today's mission: find the treats."] },
    { nickname: "Captain Couch", sayings: ["The couch is under my protection.", "Undefeated since breakfast."] },
    { nickname: "The Treat Detective", sayings: ["I heard the snack bag.", "The case of the missing biscuit: solved."] },
    { nickname: "Sir Barks-a-Lot", sayings: ["Someone had to say something.", "I heard that. And that."] },
    { nickname: "Neighborhood Watchdog", sayings: ["Nothing gets past this porch.", "Fast enough to catch one squirrel. Probably."] },
    { nickname: "Professor Paws", sayings: ["Professional blanket inspector.", "Currently grading your snack sharing."] },
    { nickname: "Bruzer Zayne", sayings: ["Respectable daytime name. Suspiciously calm.", "It's on the tag. The other tag."] },
    { nickname: "The Dark Zay", sayings: ["Quiet all day. Legendary after dinner.", "Same dog, longer cape."] },
  ],
  profileType: "family",
  adoptionStatus: "home",
  primaryImage: "/isaiah.jpg",
  primaryImageAlt: "Isaiah, a black-and-white dog, sitting very still and looking directly at the camera",
  intro: [
    "Family dog by day. Batdog after dinner.",
    "Real, rescued, and extremely not for adoption.",
  ],
  verifiedFacts: [
    { label: "Real name: Isaiah — it's on the tag", source: "owner" },
    { label: "Family dog, already home", source: "owner" },
    { label: "Adopted from Home 2 Home Canine Orphanage", source: "owner" },
    { label: "St. Louis area", source: "owner" },
    { label: "Black and white coat", source: "owner" },
  ],
  shelter: { name: "Home 2 Home Canine Orphanage", url: "https://home2homecanineorphanage.org/adopt" },
  location: "St. Louis area",
  shareText:
    "Meet Isaiah — a.k.a. Batdog. One very good boy, one trading card at a time. He already has a home; lots of dogs near you still need one.",
  seoTitle: "Isaiah — Batdog · Fun Dog Trading Cards",
  seoDescription:
    "Isaiah: family dog, featured card Batdog. Spin a new card, share today's, then meet a dog near you who still needs a home.",
  theme: { accent: "#2DD4BF" },
};

const PROFILES: Record<string, DogProfileV1> = {
  [isaiah.slug]: isaiah,
};

export function getDogProfile(slug: string): DogProfileV1 | null {
  // All-digit paths are live rescue listings, never local profiles.
  if (/^\d+$/.test(slug)) return null;
  return PROFILES[slug.toLowerCase()] ?? null;
}

export function listDogProfiles(): DogProfileV1[] {
  return Object.values(PROFILES);
}
