// The Name Book — hand-written nicknames, one entry per dog name.
//
// This is the curation layer of Fun Dog Trading Cards. Every name here was
// written for a specific real dog on the live listings (breed, age, and
// size in view), the way Isaiah's locked seven were written for Isaiah.
// Nothing in this file is a template: no entry is reused for another name,
// and published decks are built almost entirely from this book plus the
// dog's verified listing facts.
//
// First card of every entry is the hero — the deck opener.
//
// House rules for every name in this file:
//   · one to four words, easy for a kid to say out loud
//   · the dog's real name stays recognizable (or the pun explains itself)
//   · rhyme, sound-alike, food, music, or story — never a rank or title
//   · no real-world claims (see CLAIM_TERMS), no machinery language
//   · sayings fit on a card: 70 characters max
//   · nothing here may collide with another dog's cards — the audit test
//     builds every published deck and fails on any shared nickname

export type BookCard = { n: string; s?: string };

const B = (n: string, s?: string): BookCard => ({ n, s });

/** Keyed by lowercase display name (see parseListingName). */
export const NAME_BOOK: Record<string, BookCard[]> = {
  abby: [
    B("Abby Road", "Now crossing the living room in single file."),
    B("Dear Abby", "Advice: adopt the dog."),
    B("Abby Dabby", "Twice the Abby, twice the wag."),
    B("Gabby Abby", "Has opinions about the mail."),
    B("Abba", "The dancing queen of the dog run."),
    B("Abs", "Core strength: nap-certified."),
    B("Abby the Pittie", "Says so right on the listing."),
  ],
  adolfo: [
    B("Adolfo Alfredo", "Extra saucy. Zero noodles."),
    B("Big Al", "Everyone's favorite regular."),
    B("Dolfo", "Big name, bigger heart."),
    B("Alfie", "The friendly abbreviation."),
    B("Fo-Fo", "Answers on the second Fo."),
    B("Dolf", "One syllable of mastiff."),
  ],
  amara: [
    B("Amara Marinara", "Best served with meatballs nearby."),
    B("Amara Mia", "That's amore, in mastiff size."),
    B("Marmalade", "Sweet, spreadable, sticks to you."),
    B("Amara Bambina", "Italy's sweetest export."),
    B("Amara Cara", "It means 'dear.' Accurate."),
    B("Ama", "Short and adoring."),
  ],
  amarillo: [
    B("Amarillo Armadillo", "Rolls up. Refuses to un-roll before noon."),
    B("Yellow Rose", "The yellow rose of the whole block."),
    B("Amarillo by Morning", "Home by suppertime."),
    B("Cheerio Amarillo", "Breakfast greeting champion."),
    B("Rillo", "The cozy short version."),
    B("Lil Rilla", "Small-town name, big-city nose."),
    B("Amarillo the Staffy", "Texas name, St. Louis heart."),
  ],
  angus: [
    B("Angus Beef", "One hundred percent grass-fed goodness."),
    B("Angus McBangus", "Say it three times fast."),
    B("Gus the Bus", "All aboard. Next stop: dinner."),
    B("Gus", "The classic. The original."),
    B("Gus-Gus", "So nice they named Gus twice."),
    B("Haggis Angus", "Scotland's proudest export."),
  ],
  anita: [
    B("Anita Nap", "Say it out loud. She agrees."),
    B("Anita Snack", "Also true at all hours."),
    B("Anita Belly Rub", "Third request today. Granted."),
    B("Anita Walk", "The full trilogy of needs."),
    B("Anita Friend", "The truest one of all."),
    B("Nita", "Sweet and simple."),
  ],
  annie: [
    B("Annie Oakley", "Sharpest nose in the West."),
    B("Annie Bananie", "Goes bananas for a doorbell."),
    B("Granny Annie", "Wise, unhurried, always right."),
    B("Tomorrow Annie", "The sun comes out wherever she naps."),
    B("Annie Get Your Bone", "She got it. It's hers now."),
    B("Nan", "The one-syllable sweetheart."),
  ],
  ash: [
    B("Ash the Flash", "Blink and she's on the couch."),
    B("Ash Ketchum", "Gotta catch that tennis ball."),
    B("Ash the Splash", "Water bowl? More like water park."),
    B("Little Ember", "The warm glow of the litter."),
    B("Ashers", "One name, forty nicknames incoming."),
    B("Ash-Ash", "Twice as quick."),
  ],
  "asher blue": [
    B("Asher Dasher", "Through the yard in a one-dog sleigh."),
    B("Ash Blue", "The coolest shade on four legs."),
    B("Dash", "Middle name: Gone Already."),
    B("Blue Asher", "Same handsome, reversed."),
    B("Asher the Smasher", "Of cuddle records, specifically."),
    B("Blue Steel Asher", "That look. You know the one."),
    B("Asher Blue the Staffy", "Says so right on the listing."),
  ],
  astrid: [
    B("Fastrid", "Whippet rules: fastest nap wins too."),
    B("Astrid the Asteroid", "Approaching at incredible speed."),
    B("Astro", "Cleared for launch."),
    B("Astrid the Star", "The one the telescope's for."),
    B("Asta La Vista", "She'll be back. At dinner."),
    B("Trid", "Rhymes with 'did a zoomie.'"),
    B("Whippet Good Astrid", "When a problem comes along, she zooms."),
  ],
  atlas: [
    B("Atlas at Last", "Worth the whole map."),
    B("Road Atlas", "Knows every route to the park."),
    B("Attie", "Small word for a whole world."),
    B("Atlas the Compass", "Always points home."),
    B("At-At", "Walks like one before coffee."),
    B("World Atlas", "Every page is a walk."),
  ],
  auggie: [
    B("Auggie Doggie", "The original very good doggie."),
    B("Auggie Fresh", "So fresh and so clean."),
    B("Auggie Froggie", "Leaps first, looks later."),
    B("Doggie Auggie", "Same joke, still funny."),
    B("Augs", "The huggable abbreviation."),
    B("Aug", "Short for awesome, basically."),
    B("Auggie the Pittie", "Doggie, officially."),
  ],
  ayra: [
    B("Ayra Tiara", "Fanciest head in the room."),
    B("Cuddly Ayra", "Terrier outside, teddy inside."),
    B("Ay-Ay", "The answer is always Ay-Ay."),
    B("Ayra Sahara", "Sunny disposition, desert-dry humor."),
    B("Ayra the Stara", "Rhymes because she earned it."),
    B("Rah-Rah Ayra", "Her own cheer squad."),
  ],
  bailey: [
    B("Bailey Biscuit", "Warm, golden, gone by morning."),
    B("Bay Leaf", "Adds flavor to everything."),
    B("Bay-Bay", "Once for hello, twice for dinner."),
    B("Bailey Ukulele", "Small, cheerful, always in tune."),
    B("Frenchie Bailey", "Oui oui, madame."),
    B("Bails", "Always bails you out of a bad day."),
    B("Old Bay Bailey", "Perfectly seasoned."),
  ],
  bandit: [
    B("Smokey Bandit", "Eastbound and down the hallway."),
    B("Snack Bandit", "The crumbs never stood a chance."),
    B("Bandito", "Wanted: for stealing hearts."),
    B("Gentleman Bandit", "Takes only what's freely given. And crumbs."),
    B("Ban-Dan", "The distinguished senior partner."),
    B("Heart Bandit", "His biggest heist yet: yours."),
  ],
  basque: [
    B("Basque in the Sun", "Found his spot. Staying."),
    B("Basquet", "A very good boy in basket form."),
  ],
  baxter: [
    B("Baxter the Boxer", "It rhymes AND it's true."),
    B("Bax", "Short name, long zoomies."),
    B("Backflip Baxter", "Stuck the landing. Mostly."),
    B("Baxy", "The bouncy diminutive."),
    B("Saxophone Baxter", "Smooth jazz howls nightly."),
    B("Bax-a-Million", "Feeling like one, daily."),
    B("Bax to the Future", "Where he's going, he doesn't need roads."),
  ],
  bea: [
    B("Bumble Bea", "Small. Buzzy. Surprisingly loud."),
    B("Bea Mine", "Valentine, all year long."),
    B("Spelling Bea", "W-A-L-K. She knows."),
    B("Bea-Bea", "Double the buzz."),
    B("Honey Bea", "Sweetest thing in the hive."),
    B("Letter Bea", "Second in the alphabet, first in your heart."),
  ],
  beans: [
    B("Cool Beans", "The coolest beans in the whole pot."),
    B("Jumping Beans", "Straight up. No warning."),
    B("Beanie", "Fits right on your lap."),
    B("Bean Burrito", "Wrapped in a blanket by 8 p.m."),
    B("Full of Beans", "The listing said so. It's true."),
    B("Beanie Baby", "Collector's item. One of one."),
  ],
  bella: [
    B("Bellissima", "The fanciest bark in the building."),
    B("Mozzarella Bella", "Extra cheesy. Zero regrets."),
    B("Tinker Bella", "Clap if you believe in dinner."),
    B("Bella Boo", "Official household sweetheart."),
    B("Bella of the Ball", "Every ball. Tennis included."),
    B("Bell", "Rings once, comes running."),
  ],
  "bella blue": [
    B("Bella Blueberry", "Sweetest berry on the bush."),
    B("Blue Jean Bella", "Comfortable, classic, always fits."),
    B("Bella Blue Sky", "Forecast: sunny with a chance of wag."),
    B("True Blue Bella", "Loyalty in her actual name."),
    B("Bella Blue Ribbon", "Best in show, obviously."),
    B("Blue", "The short version. Still award-winning."),
    B("Bluebird Bella", "Happiness with feathers? No — fur."),
  ],
  belladonna: [
    B("Bella Donut", "Sweet with a hole lot of love."),
    B("Prima Belladonna", "The show starts when she enters."),
    B("Donna", "Short, sweet, and in charge."),
    B("Bella Madonna", "Strikes a pose at every window."),
    B("Donna Prima", "First in line, always."),
    B("Bells and Whistles", "The fully loaded model."),
  ],
  bellamy: [
    B("Jelly Bellamy", "Every flavor is her favorite."),
    B("Bellamy Salami", "Deli counter's most loyal fan."),
    B("Belly", "Rubs accepted here, daily."),
    B("Bellamy the Beagle", "Nose down, tail up, heart open."),
    B("Bellamy Jamboree", "A one-beagle festival."),
    B("Bells", "Rings true."),
  ],
  bernard: [
    B("Bear-nard", "Half Bernese, half actual bear."),
    B("Bernie Bear", "Warmest spot in the house."),
    B("Bernie", "The people's pup."),
    B("Barnyard Bernard", "Big enough to have his own zip code."),
    B("Bern", "Short for 'enormous sweetheart.'"),
    B("Bernese Bernard", "Mountain dog, molehill worries."),
  ],
  berry: [
    B("Very Berry", "Extra flavor in every wag."),
    B("Strawberry", "The sweetest pick of the patch."),
    B("Berry the Lab", "Freshly picked, ready to go home."),
    B("Blueberry Berry", "Double the fruit, double the fun."),
    B("Berry Fast", "Especially at dinnertime."),
    B("Bear-y", "Spelled wrong, hugged right."),
  ],
  betsy: [
    B("Betsy Boop", "Boop the snoot. She insists."),
    B("Betsy Ross", "Sewing the family together since day one."),
    B("Bets", "All bets on the little one."),
    B("Betsy Wetsy Kisses", "Fair warning."),
    B("Bitsy Betsy", "Itsy, even."),
    B("Bet", "A sure one."),
  ],
  "betty sue": [
    B("Betty Sue Bayou", "A hound song in two syllables."),
    B("Betty Spaghetti", "Twirls right into your heart."),
    B("Sue-Sue", "Sweet as sweet tea."),
    B("Peggy Sue's Cousin", "Buddy Holly would approve."),
    B("Betty Blue Tick", "Coonhound royalty, no titles needed."),
    B("Miss Betty Sue", "Southern manners, muddy paws."),
    B("Sweet Home Betty Sue", "Where the tail is. Wherever you are."),
  ],
  bilbo: [
    B("Bilbo Waggins", "Off on an unexpected walkies."),
    B("Second Breakfast Bilbo", "And elevenses. And lunch."),
    B("Bibbo", "Smallest hero in the shire."),
    B("Bilbo the Brave", "Dragons fear him. Vacuums, mutual."),
    B("There and Back Bilbo", "Every walk's an epic."),
    B("Bilbs", "The pocket-sized adventurer."),
  ],
  "billie jo": [
    B("Billie Jo Banjo", "Front porch music, tail percussion."),
    B("Billie Jean", "The best moves on the dance floor."),
    B("Jo-Jo", "Comes running on the second Jo."),
    B("Billie the Kid", "Youngest outlaw in the west wing."),
    B("Billie Jolene", "Please don't take her home... unless it's yours."),
    B("Lil Jo", "The country-song shorthand."),
  ],
  blitz: [
    B("Blitzen", "On loan from the North Pole."),
    B("Chocolate Blitz", "Seventy percent cocoa, thirty percent nap."),
    B("Blitzy", "Old dog, lightning name."),
    B("Blitz Please", "The politest thunder."),
    B("Cocoa Blitz", "Warm, brown, best by the fire."),
    B("Blitzer", "Breaking news: very good boy."),
  ],
  bluebell: [
    B("Bluebelle", "The belle of every backyard ball."),
    B("Bluey", "The realest blue heeler-at-heart."),
    B("Bell Pepper", "A little crunchy, very sweet."),
    B("Bluebell Barbell", "Does her reps at the food bowl."),
    B("Bloom", "A flower name deserves one."),
    B("Southern Bluebell", "Charm by the acre."),
    B("Bluebell the Pittie", "A flower with a wag."),
  ],
  bobbie: [
    B("Bobbie Sox", "Hop, bop, never stops."),
    B("Bibbidi Bobbie", "Boo. You're her favorite now."),
    B("Bob-Bob", "Bobs for treats. Undefeated."),
    B("Bobbie Pin", "Small, essential, holds it all together."),
    B("Bobbin Bobbie", "Sews up your whole heart."),
    B("Bobs", "Plural, because one name isn't enough."),
    B("Bobbie the Pittie", "The listing's sweetest line item."),
  ],
  "bobby boo": [
    B("Bobby Boo-Bear", "Softest beagle in three counties."),
    B("Peekaboo Bobby", "Found you. Every time."),
    B("Boo", "One syllable. Whole heart."),
    B("Bobby Boo-Boo", "Kisses make everything better."),
    B("Halloween Bobby", "Boo, but make it cute."),
    B("Snoozy Boo", "Champion of the afternoon nap circuit."),
  ],
  bonita: [
    B("Bonita Banana", "Top of the bunch."),
    B("Bonita Chiquita", "Little and lovely, says the name twice."),
    B("Bonnie", "Bonnie without a Clyde. Apply within."),
    B("Bon-Bon", "Candy with no wrapper. All sweet."),
    B("Señorita Bonita", "The prettiest name says it twice."),
    B("Neat-a Bonita", "The rhyme writes itself."),
  ],
  boomer: [
    B("Boomer Zoomer", "Zero to zoomies in one second flat."),
    B("Sonic Boomer", "You'll hear the happiness first."),
    B("Boom-Boom", "Tail against the wall. All night."),
    B("Boomerang Akita", "Throws himself. Comes back."),
    B("Boombox", "Plays one song: joy."),
    B("Booms", "The friendly thunder."),
  ],
  brada: [
    B("Abrada Cadabra", "Poof. Your treat is gone."),
    B("Brada Prada", "Designer heart, shelter price."),
    B("Bee-Bee", "Small name for a big deal."),
    B("Brada the Comforter", "Weighted blanket, self-warming."),
    B("Rah-Rah Brada", "Cheers for dinner. Loudly."),
    B("Brah-da", "Totally chill, dude."),
    B("Brada the Terrier", "Says so right on the listing."),
  ],
  buddy: [
    B("Buddy the Elf", "Smiling's his favorite."),
    B("Best Bud", "It's official. It's him."),
    B("Buddy Guy", "Got them front-porch blues. And a ball."),
    B("Buddy System", "Never swim, nap, or snack alone."),
    B("Bud", "Everything a name needs."),
    B("Buddy Boy", "The full front-porch greeting."),
    B("Buddy the Lab", "The friend the breed was famous for."),
  ],
  buttons: [
    B("Belly Buttons", "Press once for instant friendship."),
    B("Button Nose", "Boop-certified."),
    B("Cute as Buttons", "Scientifically confirmed."),
    B("Buttons the Plott", "Rare breed, rarer heart."),
    B("Push My Buttons", "Instructions: pet here."),
    B("Butterscotch Buttons", "The candy dish of dogs."),
    B("Buttons & Bows", "Gift-wrapped year-round."),
  ],
  carl: [
    B("Carlito", "Smooth operator, kibble division."),
    B("Gnarly Carl", "Catches waves of couch cushions."),
    B("Carlos", "The same good boy, in formal wear."),
    B("Cannonball Carl", "Clears the couch in one leap."),
    B("Carl the Good Ol' Boy", "Front porch certified."),
    B("Carly Barley", "Farm-fresh rhymes."),
  ],
  carol: [
    B("Sweet Caroline", "Bum bum bum. Dinner never felt so good."),
    B("Carol of the Bells", "Rings the food bowl like a chime."),
    B("Care Bear Carol", "Caring is her superpower."),
    B("Caroling Carol", "Howls in the key of joy."),
    B("Caro", "The cozy short version."),
    B("Christmas in July Carol", "Festive year-round."),
    B("Carol the Lab", "The classic carol, sung in wags."),
  ],
  cheetah: [
    B("Cheeto", "Dangerously snackable."),
    B("Cheetah Girl", "Fastest lab in the savanna. Er, backyard."),
    B("Chee-Chee", "Quick name for a quick girl."),
    B("Cheetah Print", "Leaves paw prints everywhere."),
    B("Turbo Cheetah", "Zero to snuggle in record time."),
    B("Cheetah Pita", "Fast food, the cuddly kind."),
    B("Cheetah the Lab", "Says so right on the listing."),
  ],
  chevy: [
    B("Chevy Chase", "Chases everything. Catches naps."),
    B("Chevy the Aussie", "All-wheel drive, fur trim package."),
    B("Chev", "Runs great. One careful owner wanted."),
    B("Heavy Chevy Love", "Leans on you with her whole heart."),
    B("Chevy Levy", "Drove her to the levee. She drove home."),
    B("Vroom Chevy", "Starts on the first pet."),
    B("Chevy Bel Air", "The 1957 classic, reissued in fur."),
  ],
  "christmas carol": [
    B("Merry Christmas Carol", "Every day is December with her."),
    B("Christmas Cookie", "Sweet, warm, disappears fast."),
    B("Christmas Morning", "That feeling, but with fur."),
    B("Jingle All the Carol", "Hear her coming. Smile early."),
    B("Christmas Present", "Already wrapped in fur."),
    B("Carol the Elf", "Santa's St. Louis branch office."),
  ],
  cinnamon: [
    B("Cinnamon Roll", "Warm, sweet, impossible to resist."),
    B("Cinnamon Toast", "Crunchy outside, soft inside."),
    B("Cinnamon Sugar", "Extra sprinkled on everything."),
    B("Cinna", "The short sweet sprinkle."),
    B("Cinnamon Swirl", "Watch her chase her tail."),
    B("Spice Girl Cinnamon", "Tell you what she wants: treats."),
  ],
  cleo: [
    B("Cleopatra", "The original Cleo. Accept no substitutes."),
    B("Oreo Cleo", "Twist, lick, adore."),
    B("Cleo of the Nile", "Floats above the drama."),
    B("Cleo-Cleo", "Twice as regal."),
    B("Romeo and Cleo", "You're Romeo in this scenario."),
    B("Clee", "Casual Friday royalty."),
  ],
  colby: [
    B("Colby Jack", "Half cheese, half very good boy."),
    B("Cole Train", "All aboard. No brakes on the love."),
    B("Cheesy Colby", "The good kind of cheesy."),
    B("Colby Cheddar Swirl", "The deluxe block."),
    B("Cole", "Smooth as the other side of the pillow."),
    B("Colbs", "The friendly wedge."),
    B("Colby-Wan Kenobi", "These are the treats you're looking for."),
  ],
  cordelia: [
    B("Cordelia Bedelia", "Takes 'go fetch' delightfully literally."),
    B("Accordion Cordelia", "Squeeze her name and it sings."),
    B("Cordy", "Short and sweet, like her patience for lunch."),
    B("Delia", "The middle of the name, the center of attention."),
    B("Cordelia the Bulldog", "Shakespeare never wrote one this good."),
    B("Cord", "Strong connection, instant bond."),
  ],
  cruiser: [
    B("Cruise Control", "Set to steady wag."),
    B("Tom Cruiser", "Does his own stunts."),
    B("Lil Cruiser", "Compact model, full features."),
    B("Cruiser the Heeler", "Herds you gently toward the treat aisle."),
    B("Slow Cruise", "Naps at five miles per hour."),
    B("Cruise Ship", "All-inclusive cuddles."),
  ],
  darla: [
    B("Darla Darling", "First name Darla, middle name Darling."),
    B("Starla Darla", "The brightest one in the yard."),
    B("Dar-Dar", "Twice the name, twice the tail."),
    B("Darlin' Darla", "Say it with a drawl."),
    B("Darla the Marvel", "No cape required."),
    B("Dars", "Short, sweet, wiggly."),
    B("Darla the Staffy", "Says so right on the listing."),
  ],
  dart: [
    B("Dart the Sweetheart", "Fast name, soft center."),
    B("Lightning Dart", "Struck the couch twice already."),
    B("Bullseye Dart", "Lands in your lap. Every throw."),
    B("Dart Board", "The whole game comes to him."),
    B("Darting Dart", "Verb and noun, simultaneously."),
    B("Dart the Heart", "The rhyme tells the truth."),
    B("Dart the Pittie", "Fastest smile in the listing."),
  ],
  diesel: [
    B("Vin Diesel", "Family. It's all about family."),
    B("Diesel the Wolfhound", "Tall, dark, and shaggy."),
    B("Turbo Diesel", "Slow to start, unstoppable once warm."),
    B("Diesel Fuel", "Runs on kibble and compliments."),
    B("Deez", "The casual model."),
    B("Full Tank Diesel", "Topped off with love."),
  ],
  dottie: [
    B("Polka Dottie", "Dances in spots."),
    B("Dottie Spaghetti", "A little saucy, very sweet."),
    B("Dot", "Small mark, big heart."),
    B("Dot-to-Dot", "Connect them all: they spell HOME."),
    B("Dottie the Softie", "Senior-grade snuggling."),
    B("Sweet Spot Dottie", "She IS the sweet spot."),
  ],
  dumpling: [
    B("Soup Dumpling", "Warm, wrinkly, full of love."),
    B("Pot Sticker", "Sticks right to your side."),
    B("Sweet Dumpling", "Steamed fresh daily."),
    B("Dumpling the Shar Pei", "Extra folds, extra love."),
    B("Dim Sum Dumpling", "A little bit of everything good."),
    B("Dumps", "Never down in them."),
    B("Bao-Bao", "The steamed-bun spelling of adorable."),
  ],
  elmo: [
    B("Tickle-Me-Elmo", "Belly rubs cause uncontrollable giggling."),
    B("Elmo's World", "We all just live in it."),
    B("Mo", "Two letters, all heart."),
    B("Elmo the Heeler", "La la la la, herding time."),
    B("El Mo Grande", "The big friendly one."),
    B("Elbows Elmo", "Claims the whole armrest."),
  ],
  elsa: [
    B("Elsa Salsa", "Spicier than the movie version."),
    B("Let-It-Go Elsa", "The ball, specifically. He won't."),
    B("Elsie", "The cool one at the dog park."),
    B("Elsa the Hound", "Sings 'Into the Unknown' at sirens."),
    B("Frozen Treats Elsa", "His favorite genre of snack."),
    B("El", "Short. Cool. Collected."),
  ],
  fiona: [
    B("Fiona Bologna", "First name Fiona, last name lunch."),
    B("Fee-Fi-Fo", "Fum. She smells the treats of an Englishman."),
    B("Fi-Fi", "Fancy on the outside, goofball inside."),
    B("Fiona Pepperona", "A little spicy, extra cheese."),
    B("Fabulous Fiona", "Swamp castle optional."),
    B("Fee", "Paid in full with kisses."),
  ],
  foster: [
    B("Forever Foster", "The name's temporary. The home shouldn't be."),
    B("Fozzie", "Wocka wocka. Nailed it."),
    B("Foss", "One-syllable friend for life."),
    B("Foster the People", "Comes with his own theme music."),
    B("Foster Home Graduate", "Top of his class in cuddling."),
    B("Fost", "The friendly shorthand."),
    B("Coffee with Foster", "The best part of waking up."),
  ],
  "foxy roxy": [
    B("Rock Star Roxy", "Sold-out shows in the backyard nightly."),
    B("Foxtrot Roxy", "Slow, slow, quick-quick, zoomies."),
    B("Rox", "Solid as one."),
    B("Roxy Moxie", "Full of it, gloriously."),
    B("Foxy Loxy", "The storybook version, minus the drama."),
    B("Roxy the Terrier", "Terrier-fic, honestly."),
    B("Roxy Roll", "Like rock and roll, but fluffier."),
  ],
  freckles: [
    B("Freckle Face", "Every spot placed by hand, clearly."),
    B("Sprinkles", "Extra toppings included."),
    B("Frecks", "Connect the dots to her heart."),
    B("Freckles the Heeler", "Spotted AND speckled. Deluxe."),
    B("Summer Freckles", "Sunshine left its signature."),
    B("Speckles", "The alternate spelling of adorable."),
    B("Dot-Dash Freckles", "Morse code for 'very good girl.'"),
  ],
  garth: [
    B("Garth Barks", "Friends in low places. Mostly under the table."),
    B("Party On Garth", "Excellent. Woof."),
    B("Gar-Gar", "The encore version."),
    B("Garth Vibes", "Country heart, city manners."),
    B("Rodeo Garth", "Eight seconds of zoomies, minimum."),
    B("Garth the Good", "Standin' outside the fire. Napping."),
    B("Garth the Pittie", "Country heart, city listing."),
  ],
  gloria: [
    B("G-L-O-R-I-A", "Spell it out. She'll come running."),
    B("Glo-Worm", "Lights up the whole room."),
    B("Glorious Gloria", "Exactly as advertised."),
    B("Glo", "Short for glowing."),
    B("Gloria the Rottie", "Velvet hippo, deluxe edition."),
    B("Morning Gloria", "Blooms at breakfast."),
    B("Glory Days Gloria", "They're all still ahead of her."),
  ],
  goodfellow: [
    B("The Goodest Fellow", "Grammar experts agree: goodest."),
    B("Goodfella", "As far back as he can remember, wanted a home."),
    B("Fella", "Just a real one."),
    B("Goodfellow the Gent", "Holds the door with his nose."),
    B("Nice Guy Goodfellow", "Finishes first, actually."),
    B("Fellow Traveler", "Shotgun's his seat now."),
  ],
  gordy: [
    B("Flash Gordy", "Savior of the universe. And dropped fries."),
    B("Gordo", "Big vibes, bigger heart."),
    B("Gord", "Solid. Dependable. Snores."),
    B("Gordy the Great-y", "The rhyme insists."),
    B("Gordy Shortie", "Whatever his size, he's perfect."),
    B("Motown Gordy", "Berry Gordy's spirit animal."),
    B("Gords", "The plural of good."),
  ],
  gracie: [
    B("Amazing Gracie", "How sweet the pound. Er, sound."),
    B("Gracie Goose", "Honks at squirrels, waddles to bed."),
    B("Saving Gracie", "Or is she saving you?"),
    B("Gracie the Mastiff", "160 pounds of please-hold-me."),
    B("Grace Period", "Extended indefinitely."),
    B("Gray-Gray", "The gentle repeat."),
  ],
  graham: [
    B("Graham Cracker", "Best part of the s'more."),
    B("S'mores Graham", "Sticky, sweet, campfire-approved."),
    B("Graham Slam", "Bases loaded. Tail wagging."),
    B("Graham the Staffy", "Solid as a graham-built house."),
    B("Teddy Graham", "Snack-sized heart, full-sized dog."),
    B("Grammy", "Award-winning, obviously."),
  ],
  gremlin: [
    B("Gizmo", "The cute kind. Promise."),
    B("Grem", "Do not feed after midnight. He'll ask anyway."),
    B("Lil Gremlin", "Mischief in travel size."),
    B("Gremlin the Goblin", "Of stolen socks and hearts."),
    B("Grumbles", "His purr. Sort of."),
    B("Gremmy", "The lovable menace."),
  ],
  grover: [
    B("Grover the Rover", "Near. Far. Wherever the treats are."),
    B("Grover Cleveland", "The only Grover to serve two lap terms."),
    B("Grove", "A tiny forest of good."),
    B("Grover from the Street", "The furry blue energy, in pit form."),
    B("Groovy Grover", "Peace, love, and puppy breath."),
    B("Baby Grove", "Still growing his rings."),
  ],
  guido: [
    B("Guido Gelato", "Sweetest scoop in the old country."),
    B("Guido Mosquito", "Big dog, tiny buzz."),
    B("Gui-Gui", "Twice as Italian."),
    B("Guido the Mastiff", "Nonna's favorite grandson."),
    B("Guido Burrito", "Wraps himself in every blanket."),
    B("Gweeds", "The casual cut."),
  ],
  gunner: [
    B("Gunner the Runner", "Laps before breakfast. Naps after."),
    B("Top Gunner", "Feels the need. The need for treats."),
    B("Gunny", "Reporting for cuddle duty."),
    B("Gunner the Rottie", "Big frame, bigger lean."),
    B("Front Runner", "For best boy, every year."),
    B("Guns", "Of the hug variety."),
  ],
  hailey: [
    B("Hailey's Comet", "Comes around way more than every 76 years."),
    B("Hailstorm", "Small, fast, surprisingly loud."),
    B("Hails", "The forecast is friendly."),
    B("Hailey Bailey Bo", "The playground chant version."),
    B("Hailey the Beagle", "A howl you can set your watch to."),
    B("Hay-Hay", "The happy repeat."),
    B("Hailey-lujah", "The choir sings when she arrives."),
  ],
  harley: [
    B("Harley the Hog", "Born to be mild."),
    B("Vroom Vroom Harley", "Idles loud, rides smooth."),
    B("Harls", "Low rider, high spirits."),
    B("Harley Gnarly", "In the raddest way."),
    B("Sidecar Harley", "Your co-pilot, reporting."),
    B("Harley Hugs", "Full throttle affection."),
  ],
  harrison: [
    B("Harrison Fetch", "The chosen one, obviously."),
    B("Indiana Bones", "It belongs in a toy bin!"),
    B("Harry", "Regular guy. Legendary heart."),
    B("Harrison the Handsome", "The listing photo agrees."),
    B("Harris", "Distinguished. Drooly."),
    B("Hare-Chaser Harrison", "Dreams big, naps bigger."),
    B("Harrison the Staffy", "Says so right on the listing."),
  ],
  hawkeye: [
    B("Ol' Hawk Eyes", "Sees a snack at forty paces."),
    B("Tomahawk", "Sharpest profile in the pack."),
    B("Hawky", "Soars straight to the couch."),
    B("Hawkeye the Shepherd", "Watches over the whole flock. You're the flock."),
    B("Hawk", "Circles twice, lands on the bed."),
    B("Silver Hawk", "The distinguished senior model."),
  ],
  hazel: [
    B("Hazelnut", "Sweetest thing you can spread on a couch."),
    B("Hazel Basil", "Fresh, fragrant, a little peppery."),
    B("Hazy Days", "Every one of them good."),
    B("Hazel Eyes", "The name checks out."),
    B("Haze", "Rolls in gently, stays all day."),
    B("Witch Hazel", "The soothing kind."),
  ],
  "hazel grace": [
    B("Sweet Hazel Grace", "Okay? Okay."),
    B("Hazy Grazy", "A little dreamy, a lot lovable."),
    B("Grace-Face", "The look that gets seconds at dinner."),
    B("Grace Note", "The little extra that makes the song."),
    B("Hazel Grace the Ace", "Highest card in the deck."),
    B("Graceful Hazel", "Mostly. Except near tennis balls."),
  ],
  hersey: [
    B("Hersey Kisses", "Free, unlimited, slightly slobbery."),
    B("Hersey Bar", "Sweetness in standard size."),
    B("Chocolate Hersey", "Warning: irresistibly sweet."),
    B("Hersey Park", "The amusement is built in."),
    B("Hersey Squeeze", "The huggable wrapper."),
    B("Hers", "And yours, hopefully."),
    B("Cocoa Hersey", "Best served warm."),
  ],
  hobbs: [
    B("Hobbs the Tiger", "Imaginary best friend, fully real."),
    B("Hobnob Hobbs", "Mingles professionally."),
    B("Hobbsie", "The neighborhood philosopher."),
    B("Calvin's Hobbs", "Adventure is out there. So are naps."),
    B("Hobbs the Beagle", "Ears first, everywhere."),
    B("Hobby", "The best one you'll ever pick up."),
    B("Hobbs the Pounce", "Tigers are great. He agrees."),
  ],
  holden: [
    B("Holden Hands", "Well, paws. Same thing."),
    B("Holden My Heart", "Since the moment you scrolled here."),
    B("Holden the Catcher", "In the rye, in the yard, mid-air."),
    B("Holdy", "The cozy short version."),
    B("Holden On", "Never lets go of his people."),
    B("Hold-the-Phone Holden", "Yes, that face is real."),
    B("Holden the Pittie", "Holds the record for longest lean."),
  ],
  honey: [
    B("Honey Bee", "Sweet with a busy schedule of naps."),
    B("Honey Bun", "Golden, glazed, gone in seconds."),
    B("Honey Pot", "The whole hive agrees."),
    B("Honey Baloney", "Rhymes with lunch. Fitting."),
    B("Milk and Honey", "The land of plenty is her lap."),
    B("Hon", "Short. Warm. Perfect."),
  ],
  huckleberry: [
    B("Huckleberry Pie", "Fresh out of the oven of good dogs."),
    B("Huck Finn", "River adventures, backyard edition."),
    B("Huck", "Ready to light out for the territory. Or the porch."),
    B("Huckleberry the Pointer", "Points at birds. And snacks. Mostly snacks."),
    B("Hucks", "The plural of adventure."),
    B("I'm Your Huckleberry", "She really is."),
    B("Huckleberry Friend", "Moon River's favorite kind."),
  ],
  "huey lewis": [
    B("Huey Lewis & the Nose", "That sniff? That's the power of love."),
    B("Hip to Be Huey", "It's hip to be square. And fetch."),
    B("Huey", "The news is: he's a very good boy."),
    B("Huey the Pittie", "Heart of rock and roll, still beating."),
    B("Front Page Huey", "Breaking: local dog wonderful."),
    B("Hues", "All the good ones."),
  ],
  isabel: [
    B("Ding-Dong Isabel", "Is a bell? Is a belle."),
    B("Izzy B", "Busy being the best."),
    B("Belle", "The whole ball waits for her."),
    B("Isabel the Pittie", "Rings true."),
    B("Izzy Bizzy", "Booked solid with naps."),
    B("Bella-Isabel", "The full formal flourish."),
    B("Decibel Isabel", "The volume knob goes to eleven."),
  ],
  jasper: [
    B("Jasper the Friendly Dog", "You can see this one."),
    B("Jazzy Jasper", "Smooth notes, tiny package."),
    B("Lil Jasper", "Pocket-sized, full volume."),
    B("Jasper the Chi", "Mucho heart, poquito dog."),
    B("Jaspurr", "Basically a warm cat. Don't tell him."),
    B("Jasp", "The compact classic."),
    B("Jalapeño Jasper", "Chihuahua-grade spice."),
  ],
  jax: [
    B("Jumping Jax", "The full workout, no gym required."),
    B("Jax Snacks", "Rhymes with his favorite hobby."),
    B("Action Jaxon", "Now in cinematic slow motion."),
    B("Jax of All Trades", "Master of fetch."),
    B("Jax Attack", "Of kisses. Only kisses."),
    B("Jaxy", "The bouncy diminutive."),
    B("Flapjax", "Best served in a warm stack of blankets."),
  ],
  jerky: [
    B("Beef Jerky", "Tough name, tender heart."),
    B("Turkey Jerky", "Gobbles everything."),
    B("Jerky the Border Collie", "Herds the family toward the treat jar."),
    B("Smoked Jerky", "Slow-cooked sweetness."),
    B("Snack-Grade Jerky", "Premium quality, locally sourced."),
    B("Jerky the Quirky", "In all the best ways."),
    B("Herky-Jerky", "His zoomie style has a name."),
  ],
  jermaine: [
    B("Jermaine Event", "The main event, every evening."),
    B("Jermaine the Brain", "Solved the treat jar in one afternoon."),
    B("Jer-Bear", "Soft, huggable, slightly drooly."),
    B("Jermaine Attraction", "The show everyone came to see."),
    B("Maine Man Jermaine", "Your main man, spelled fancy."),
    B("Jer", "The trusty shorthand."),
    B("Jermaine the Lab", "The family's main lab."),
  ],
  jid: [
    B("Jeddy Bear", "That's what his rescue calls him. It fits."),
    B("Jid the Kid", "Young at heart, forever."),
    B("Jiddy", "Quick name, quicker tail."),
    B("Jid-Jid", "The double-tap of joy."),
    B("Jedi Jid", "The force is strong. The fetch is stronger."),
    B("J.I.D.", "Just Incredibly Devoted."),
    B("Jid the Lab", "Three letters, one whole lab."),
  ],
  jiselle: [
    B("Jiselle Gazelle", "Leaps couches in a single bound."),
    B("Mademoiselle Jiselle", "Très magnifique."),
    B("Elle", "Cover-dog material."),
    B("Jiselle the Shepherd", "Grace with a work ethic."),
    B("Jis", "The insider's name."),
    B("Carousel Jiselle", "Round and round the yard she goes."),
  ],
  jocko: [
    B("Jocko the Jock", "Varsity fetch, all-state naps."),
    B("Jocko Choco", "Sweet to the last drop."),
    B("Jockey", "Rides shotgun like a pro."),
    B("Jocko Rococo", "Fancier than he looks."),
    B("Jock", "Team captain of the couch."),
    B("Good Talk Jocko", "Best listener in the league."),
    B("Jocko Polo", "You'll never lose him. He finds YOU."),
  ],
  journey: [
    B("Long Journey Home", "Every mile was worth it."),
    B("Journey Girl", "Don't stop believin' in her."),
    B("Sweet Journey", "The destination was your couch all along."),
    B("Journey the Explorer", "Small paws, big map."),
    B("Jern-Jern", "The baby-talk version. It happens to everyone."),
    B("Midnight Train Journey", "Going anywhere... with you."),
  ],
  kanga: [
    B("Kanga Roo", "Pouch not included. Jumps included."),
    B("Kanga-Banga", "Boing. Boing. Boing."),
    B("Roo", "The bounciest syllable."),
    B("Kanga the Presa", "Springs fully loaded."),
    B("Kangaroo Court", "Verdict: adorable."),
    B("Kangs", "The cool-kid version."),
    B("Boing-Boing Kanga", "The official sound effect."),
  ],
  karl: [
    B("Karl Barx", "Workers of the yard: unite for dinner."),
    B("Karl with a K", "Not to be confused with the other guy."),
    B("K-9 Karl", "Shepherd credentials: impeccable."),
    B("Special K", "Part of a complete family."),
    B("Kind Karl", "The K stands for that too."),
    B("Sparkle Karl", "Rhymes if you believe."),
  ],
  karma: [
    B("Good Karma", "What goes around gets belly rubs."),
    B("Karma Chameleon", "She comes and goes. Mostly comes."),
    B("Instant Karma", "Adopt her, feel amazing immediately."),
    B("Karma Farm", "Harvest: endless."),
    B("Kar-Kar", "The happy echo."),
    B("Karma the Charmer", "It rhymes because it's true."),
    B("Karma Karaoke", "Sings every song like it's hers."),
  ],
  kevin: [
    B("Kevin the Minion", "Banana enthusiast. Chaos apprentice."),
    B("Kevin the Good Egg", "Certified. Sunny side up."),
    B("Kev", "Just Kev. That's the whole bit."),
    B("Kevin from the Block", "Still real, still humble."),
    B("Kevin the Keeper", "Finders keepers. You found him."),
    B("Kevvy", "The puppy-sized version."),
  ],
  king: [
    B("King Size", "The deluxe model."),
    B("King of the Couch", "His name. His throne."),
    B("Kingston", "Same king, vacation edition."),
    B("King of Fetch", "Undisputed. Unretired."),
    B("Kingfisher", "Dives for tennis balls."),
    B("King the Shepherd", "Rules with a gentle paw."),
  ],
  kora: [
    B("Kora Explora", "Backpack optional. Snacks mandatory."),
    B("Kora Bora", "A tropical vacation with fur."),
    B("KoKo", "Twice the Ko, twice the cuddle."),
    B("Kora the Shepherd", "Young, keen, and very employed."),
    B("Kora Aurora", "The northern lights of the dog park."),
    B("Encore Kora", "The crowd demands more. She delivers."),
    B("Kora Adora", "Rhymes with how everyone feels."),
  ],
  ladder: [
    B("Laddie", "A good lad, rung by rung."),
    B("Chutes and Ladder", "He's the fun part of the game."),
    B("Step Ladder", "Helps you reach peak happiness."),
    B("Ladder the Lab", "Climbing straight up the good-boy charts."),
    B("Firehouse Ladder", "Rescue dog, literally."),
    B("Lad", "Aye, a fine one."),
  ],
  layla: [
    B("Layla Unplugged", "The acoustic version: soft and slow."),
    B("Lullaby Layla", "Falls asleep before the second verse."),
    B("Lay-Lay", "Professional layer-downer."),
    B("Layla the Lab", "Classic rock, classic dog."),
    B("Ukulele Layla", "Small song, big feelings."),
    B("Lays", "Betcha can't pet her just once."),
  ],
  legend: [
    B("Legend Has It", "And the legend is true."),
    B("Little Legend", "Big stories, beagle-sized."),
    B("Legendary", "Ask anyone at the shelter."),
    B("Legend of the Fall", "Autumn leaves are his confetti."),
    B("Live Legend", "No myth. All dog."),
    B("Homegrown Legend", "Local. Verified. Wonderful."),
    B("Legend the Beagle", "Says so right on the listing."),
  ],
  lemon: [
    B("Lemon Squeezy", "Easy peasy. That's the whole vibe."),
    B("Lemon Drop", "Sweet with a little zing."),
    B("Lemonade", "What life made when it gave us this dog."),
    B("Lemon the Dalmatian", "Lemon-spotted. It's a real thing. He's proof."),
    B("Lemon Meringue", "Fancy dessert energy."),
    B("Zest", "The secret ingredient."),
    B("Main Squeeze Lemon", "Official title, effective immediately."),
  ],
  leo: [
    B("Leo the Lion", "The mane event, in miniature."),
    B("Leonardo DiPuprio", "And the award goes to..."),
    B("Leo the Snow Lion", "Roars softly. Sheds majestically."),
    B("Leo Season", "Year-round."),
    B("Cameo Leo", "Steals every scene."),
    B("Lion Cub Leo", "The fluffy apprentice."),
    B("Leo the Eskimo", "The breed AND the rhyme."),
  ],
  liam: [
    B("Liam the Lamb", "Follows you everywhere. It's the law."),
    B("Liam Leash-On", "He will find you. He will walk you."),
    B("Li-Li", "Double the name, double the tail speed."),
    B("Liam the Cattle Pup", "Herding hearts since birth."),
    B("Dream Team Liam", "Roster of one."),
    B("Leems", "The nickname's nickname."),
  ],
  lilo: [
    B("Lilo Ohana", "Ohana means nobody gets left behind."),
    B("Aloha Lilo", "Means hello AND welcome home."),
    B("Li-Lo", "Low to the ground, high on life."),
    B("Lilo the Lab", "Small surfboard, big waves."),
    B("Hula Lilo", "Watch the tail. That's the dance."),
    B("Lils", "Little in name only."),
  ],
  linda: [
    B("Listen Linda", "No, YOU listen. It's dinner time."),
    B("Lovely Linda", "The songs were right."),
    B("Lin", "Short, sweet, herds you gently."),
    B("Linda the Border Collie", "Smartest kid in class."),
    B("Linda Means Pretty", "Spanish speakers already knew."),
    B("Lindy Hop", "Her signature move at the door."),
    B("Ladybird Linda", "Flies home every time."),
  ],
  linus: [
    B("Linus the Genius", "Great pumpkin? Found it. It was a ball."),
    B("Blanket Linus", "Security blanket sold separately."),
    B("Line", "First in line for breakfast."),
    B("Linus the Pittie", "Philosophy degree, kindergarten heart."),
    B("Ly-Ly", "The gentle repeat."),
    B("Peanuts-Approved Linus", "Good grief, he's sweet."),
    B("Linus Van Pup", "The blanket stays in the deal."),
  ],
  lisa: [
    B("Lisa Pizza", "One slice is never enough."),
    B("Mona Lisa", "That smile follows you around the room."),
    B("Lees", "Small name, masterpiece dog."),
    B("Lisa the Lab Puppy", "Fresh out of the wrapper."),
    B("Lisa the Smiler", "Mona who?"),
    B("Lisa Lisa", "So nice they sang it twice."),
  ],
  livia: [
    B("Livia the Diva", "Demands: applause, dinner, encore dinner."),
    B("Live-It-Up Livia", "Every day's a mastiff party."),
    B("Liv", "Liv, laugh, loaf."),
    B("Livia the Mastiff", "Roman empress energy."),
    B("Livia Bolivia", "Rhymes across continents."),
    B("Liv-Long Livia", "And prosper. With treats."),
  ],
  lola: [
    B("Lola Granola", "Crunchy, wholesome, full of energy."),
    B("Lola Cola", "Extra fizzy."),
    B("Lo-Lo", "Whatever Lo-Lo wants, Lo-Lo gets."),
    B("Lola Payola", "Bribes accepted in belly rubs."),
    B("Hola Lola", "Says hi to everyone. Everyone."),
    B("Lols", "The comedian of the block."),
  ],
  lonzo: [
    B("Lonzo Ball", "Drafted first overall. By your family."),
    B("Lonzo the Gonzo", "Fully committed to the bit."),
    B("Zo", "Two letters of pure pit-bull grin."),
    B("Alonzo", "The formal dinner-party version."),
    B("Lonzo Bonzo", "Maximum goof achieved."),
    B("Zo-Zo", "The encore."),
  ],
  lucious: [
    B("Lucious Delicious", "The name reviews itself."),
    B("Juicy Lucious", "One hundred percent flavor."),
    B("Lou", "The friendly abbreviation."),
    B("Lucious the Smoocher", "Rhyme-certified kisser."),
    B("Lou-Lou", "Twice the Lou, twice the love."),
    B("Luscious Locks Lucious", "Short coat. Big confidence."),
    B("Footloose Lucious", "Kicks off his Sunday paws."),
  ],
  lucky: [
    B("Lucky Charm", "Magically delightful."),
    B("Lucky Ducky", "Quacks himself up."),
    B("Lucky Number Seven", "Seven cards. He's every one."),
    B("Lucky the Pointer", "Points straight at good fortune. It's a mirror."),
    B("Luck of the Dog", "Better than the Irish."),
    B("Lucks", "In endless supply."),
    B("Lucky Streak", "Currently active. Never broken."),
  ],
  lucy: [
    B("Lucy Goosey", "Wiggles fully installed."),
    B("I Love Lucy", "You've got some snugglin' to do."),
    B("Lu-Lu", "The rerun everyone still loves."),
    B("Lucy in the Sky", "With dog biscuits."),
    B("Juicy Lucy", "The deluxe burger of puppies."),
    B("Goose", "Her alter ego."),
  ],
  luke: [
    B("Luke Skybarker", "The bark is strong with this one."),
    B("Cool Hand Luke", "Stays chill. Wins anyway."),
    B("Luke the Duke", "Royalty of the dog run, by rhyme alone."),
    B("Lukey", "The bedtime version."),
    B("Luke the Dobie", "Elegant, athletic, velcro."),
    B("Lucas", "For when he's in trouble. He never is."),
    B("Luke at That Face", "Go ahead. Try not to smile."),
  ],
  luna: [
    B("Luna Tuna", "Rhymes with dinner. Coincidence?"),
    B("Luna the Moon", "Controls the tides of treat time."),
    B("Lunabelle", "The night's softest glow."),
    B("Luna Lovegood", "Sees the best in everything."),
    B("Luna the Beagle", "Howls at her own name. It's the moon thing."),
    B("Loons", "The silly side of the moon."),
  ],
  lyle: [
    B("Lyle Lyle Chihuahua", "Smaller than a crocodile. Bigger star."),
    B("Smile Lyle", "You first. He'll match it."),
    B("Ly", "Half the name, all the heart."),
    B("Lyle the Style", "Trendsetter of the litter."),
    B("Mile-a-Minute Lyle", "Puppy speed: engaged."),
    B("Lyles", "The plural of tiny."),
  ],
  "macho man": [
    B("Macho Nacho Man", "Ooh yeah. Extra cheese."),
    B("Muchacho", "The friendliest tough guy in town."),
    B("Ooh-Yeah Macho", "Snap into a belly rub."),
    B("Macho the Pittie", "Tough name, marshmallow interior."),
    B("Nacho Average Macho", "Clearly."),
    B("Mach One", "His zoomie speed rating."),
    B("Macho Poncho", "Wears the blanket like a champion."),
  ],
  macy: [
    B("Macy's Parade", "The giant balloon, but self-inflating."),
    B("May-May", "The gentle repeat."),
    B("Macy Gray", "Sings it smoky, wags it sweet."),
    B("Macy the Sniffer", "Hound-certified nose."),
    B("Lacey Macy", "Delicate. Ish."),
    B("Mace", "Short, strong, sweet."),
  ],
  maggie: [
    B("Magpie", "Black, brilliant, collects your socks."),
    B("Maggie May", "Wake up! It's breakfast."),
    B("Magnificent Maggie", "The full formal title."),
    B("Maggie the Black Lab", "The classic in the classic color."),
    B("Mags", "The everyday magic."),
    B("Magnolia Maggie", "Southern belle of the dog park."),
  ],
  manchi: [
    B("Munchie Manchi", "Rhymes with his hobby and his heart."),
    B("Manchi Crunchy", "Extra texture, extra love."),
    B("Manch", "One syllable of solid dog."),
    B("Manchi the Pittie", "Snacks first, questions later."),
    B("Man-Man", "The friendly double."),
    B("Munch", "His verb, his vibe."),
    B("Manchi Mariachi", "The band arrives at dinnertime."),
  ],
  marissa: [
    B("Marissa the Kissa", "Free kisses, no coupon needed."),
    B("Rissy", "Small name, puppy energy."),
    B("Rissa", "Ready in three letters or less."),
    B("Marissa the Lab Puppy", "Batteries never included or needed."),
    B("Mariposa Marissa", "Spanish for butterfly. Watch her chase them."),
    B("Riss", "Quick as her zoomies."),
  ],
  marley: [
    B("Marley & Me", "The 'me' could be you."),
    B("One Love Marley", "One heart. Let's get together."),
    B("Marls", "Every little thing gonna be alright."),
    B("Jammin' Marley", "Hope you like jammin' too."),
    B("Marley the Lab", "The movie was a documentary."),
    B("Gnarly Marley", "Radical, dude."),
    B("Marley Marmalade", "Spread the word: he's sweet."),
  ],
  marshall: [
    B("Marshall Mellow", "Soft, sweet, best by the campfire."),
    B("Marshmallow", "S'more of him, please."),
    B("The Real Slim Shaggy", "Please stand up. Or roll over."),
    B("Marsh", "The soft landing."),
    B("Marshall Arts", "Black belt in play-bow."),
    B("Mallow", "The squishiest nickname available."),
    B("Marshall the Terrier", "Wire-coat optional, heart standard."),
  ],
  maui: [
    B("Big Kahuna Maui", "Rides the gnarliest couch waves."),
    B("Maui Luau", "The party arrives when he does."),
    B("Aloha Maui", "Say hello to your new island."),
    B("Maui the Pittie", "You're welcome."),
    B("Island Time Maui", "Naps have no schedule."),
    B("Mau-Mau", "The friendly island echo."),
  ],
  maverick: [
    B("Top Dog Maverick", "Feels the need. The need for fetch."),
    B("Mav", "Call sign confirmed."),
    B("Danger Zone Mav", "Highway to the dog park."),
    B("Maverick the Lab", "Flies solo. Lands in laps."),
    B("Wingman Maverick", "Never leaves yours."),
    B("Mavvy", "The off-duty call sign."),
    B("Ace Maverick", "Highest card in the sky."),
  ],
  maya: [
    B("Mamma Maya", "Here she goes again. My my."),
    B("Maya the Bee", "Sweet as honey, busy as anything."),
    B("My-My", "Yes, she's yours-yours."),
    B("Maya the Staffy", "Solid build, softer heart."),
    B("Kalamata Maya", "The fancy olive of dogs."),
    B("Maya Fedora", "Wears invisible hats beautifully."),
    B("Himalaya Maya", "Peak sweetness at altitude."),
  ],
  mayflower: [
    B("Mayflower Power", "Landed right in your heart."),
    B("May Flowers", "What April showers were for."),
    B("Petal", "The soft landing."),
    B("Mayflower the Pointer", "Compass set to home."),
    B("Flower Puppy", "Freshly sprouted."),
    B("May-May Flower", "Blooming daily."),
  ],
  medinah: [
    B("Dinah-Mite", "Small package. Big boom."),
    B("Dinah", "Someone's in the kitchen with her. Always."),
    B("Sweet Medinah", "Front nine energy, back nine naps."),
    B("Medinah the Lab", "Club champion, cuddle division."),
    B("Deenah", "Say it soft. She'll come anyway."),
    B("Hole-in-One Medinah", "Every fetch, right in the heart."),
  ],
  memphis: [
    B("Memphis Blues", "Sings for his supper. Off-key. Perfect."),
    B("Memphis BBQ", "Smoky, sweet, worth the trip."),
    B("Walking in Memphis", "Ten feet off of Beale. On a leash."),
    B("Memphis the Pit Pup", "Small king of rock and roll."),
    B("Graceland Memphis", "The house he'll rule: yours."),
    B("Memph", "Short and soulful."),
  ],
  mercy: [
    B("Mercy Me!", "The correct reaction to her face."),
    B("Have Mercy", "You will. Immediately."),
    B("Merce", "Gentle giant, short name."),
    B("Mercy the Akita", "Dignified. Except at dinner."),
    B("Mercy Rule", "Wins every cuteness contest early."),
    B("No-Mercy Cuddles", "Resistance is futile."),
  ],
  michael: [
    B("Air Michael", "Hang time measured in treats."),
    B("Mikey", "He likes it! He really likes it!"),
    B("Michael the Redbone", "Sings bass in the hound choir."),
    B("Big Mike", "The gentle economy size."),
    B("Michael Row-Your-Boat", "Ashore. To the couch. Hallelujah."),
    B("Mike Drop", "Every trick ends with one."),
  ],
  mickey: [
    B("Mickey Moose", "Bigger than a mouse. Better, too."),
    B("Hot Dog Mickey", "Hot dog, hot dog, hot diggity dog."),
    B("Mick", "The main attraction."),
    B("Mickey the Staffy", "Big ears, bigger heart. Wait, wrong guy. Right dog."),
    B("Mickster", "The club's coolest member."),
    B("Blue-Eyed Mickey", "Old soul, young tail."),
    B("Steamboat Mickey", "The original whistling classic."),
  ],
  midnight: [
    B("Midnight Snack", "Named after the best meal of the day."),
    B("Moonlight Midnight", "Glows on every walk."),
    B("Night-Night", "The last good thing you see each day."),
    B("Midnight the Black Lab", "The classic, after dark."),
    B("Stroke of Midnight", "Magic happens when he shows up."),
    B("Middy", "Daytime nickname for a nighttime name."),
  ],
  miley: [
    B("Smiley Miley", "Came in like a wrinkle-ball."),
    B("Miles of Smiles", "Measured nose to tail."),
    B("Miley the Shar Pei", "Extra fabric, extra love."),
    B("Wrinkle Ball Miley", "Came in like one. Stayed as one."),
    B("My Girl Miley", "Talkin' 'bout her."),
    B("Miles", "Goes the distance for a treat."),
  ],
  "millie ann": [
    B("Millie Vanilli", "Girl, you know it's true: adopt her."),
    B("Silly Millie", "Wire-haired and wired for fun."),
    B("Mills", "Runs the whole operation."),
    B("Millie Ann the Terrier", "Fox-terrier fancy, farm-dog fun."),
    B("Thoroughly Modern Millie", "Classic name, fresh tricks."),
    B("Millie Ann Chantilly", "Lace-curtain fancy."),
    B("Windmillie", "Spins in happy circles."),
  ],
  moby: [
    B("Moby Dog", "The great white wag."),
    B("Mo-Mo", "Small hound, epic tale."),
    B("Moby of the High Seas", "Captain of the kiddie pool."),
    B("Moby the Hound Pup", "Call him. He'll come. Probably."),
    B("Whale of a Time Moby", "Guaranteed."),
    B("Mobes", "The first mate's name for him."),
  ],
  monty: [
    B("Monty Cristo", "The count of good boys."),
    B("Monty Python", "And now for something completely adorable."),
    B("Monts", "Peak dog."),
    B("Full Monty Fetch", "Brings the ball AND the stick."),
    B("Monty the Heeler", "Always something to herd."),
    B("Monte", "The classy spelling."),
    B("Monty Carlo", "High roller of the treat table."),
  ],
  mork: [
    B("Mork from Ork", "Nanu nanu. Shazbot. Woof."),
    B("Nanu-Nanu Mork", "The official greeting at the door."),
    B("Morky", "Landed here. Staying here."),
    B("Mork the Staffy", "Out of this world, into your lap."),
    B("Egg-Ship Mork", "Arrived. Hatched. Adorable."),
    B("Morkster", "The friendly alien next door."),
  ],
  motown: [
    B("The Motown Sound", "My girl? Could be your boy."),
    B("Motown Magic", "Dancing in the street. And kitchen."),
    B("Big Mo", "The momentum is real."),
    B("Motown the Pyrenees", "The whitest wall of sound."),
    B("Hitsville Motown", "Every day's a number one."),
    B("Mo-Town Crier", "Announces dinner city-wide."),
  ],
  nala: [
    B("Nala Koala", "Clings like a marsupial. Cuddles like a queen."),
    B("Nala the Lioness", "Can you feel the love? She can."),
    B("Nal", "Husky hello in one syllable."),
    B("Nala the Husky", "Talks back. Worth it."),
    B("Impala Nala", "Leaps first, asks later."),
    B("Nay-Nay", "The playful encore."),
    B("La-La Nala", "Hums her way through breakfast."),
  ],
  neville: [
    B("Neville Longtail", "It's levi-OH-sa, not levio-SAH. Woof."),
    B("Nev", "Ten points to whoever adopts him."),
    B("Nev-Nev", "The remembrall remembers belly rubs."),
    B("Neville the Terrier", "Braver than he looks. He looks brave."),
    B("Herbology Neville", "Digs the garden. Literally."),
    B("Sword-of-Gryffindog", "Pulled it out of the toy bin."),
  ],
  nibbles: [
    B("Kibble Nibbles", "Rhymes with breakfast, lunch, and dinner."),
    B("Nibblet", "Fun size. Full flavor."),
    B("Nibs", "The finest dark chocolate of dogs."),
    B("Nibbles the Pittie", "Gentle mouth, giant heart."),
    B("Just a Nibble", "Famous last words at snack time."),
    B("Nibbly", "The verb becomes her."),
    B("Nom-Nom Nibbles", "The soundtrack of dinnertime."),
  ],
  nicholas: [
    B("Saint Nick", "Checks his list. You're on it."),
    B("Ho-Ho-Nicholas", "Delivers joy year-round."),
    B("Nick at Nite", "Classic programming, all snuggles."),
    B("Nicholas the Lab Pup", "Santa's youngest reindeer alternate."),
    B("Jolly Nicholas", "The beard grows in later."),
    B("Nicky", "Stocking-sized."),
  ],
  nicole: [
    B("Nicole Guacamole", "Extra guac, no charge."),
    B("Nikki", "Small name, mighty puppy."),
    B("Colie", "The sweetest syllables of Nicole."),
    B("Nicole the Lab Puppy", "Fresh batch, still warm."),
    B("Nicole Ravioli", "Little pillow of joy."),
    B("Nic at Noon", "Lunchtime's biggest fan."),
  ],
  olivia: [
    B("Olive", "Extra virgin cuddle oil."),
    B("Olive Oyl", "Strong to the finish, spinach optional."),
    B("Livvy", "The shepherd next door."),
    B("Olivia the Shepherd", "Runs the house. Kindly."),
    B("Olive Branch", "Peace treaty on four paws."),
    B("Via", "The scenic route to your heart."),
  ],
  otis: [
    B("Adventures of Otis", "Milo's been waiting for a sequel."),
    B("Otie", "Sittin' on the porch of the bay."),
    B("Otis the Elevator", "Always lifts you up."),
    B("Otis Redding-Ready", "Try a little tenderness. He'll match it."),
    B("Otis the Terrier", "Small dog. Feature film energy."),
    B("O-T", "The varsity jacket version."),
    B("Oats", "Steady as oatmeal, twice as warm."),
  ],
  otter: [
    B("Otter Space", "One small step for dog."),
    B("Otter Pop", "The coolest treat of summer."),
    B("Sea Otter", "Floats through life holding your hand."),
    B("Otter the Pittie", "Sleek, playful, holds hands. Really."),
    B("Otterly Adorable", "The pun was unavoidable."),
    B("Ott", "The compact model."),
    B("Significant Otter", "The one you've been looking for."),
  ],
  otto: [
    B("Otto-Matic", "Sits, stays, loves. No manual needed."),
    B("Otto-Mobile", "Zero to snuggle in 3.5 seconds."),
    B("Otto the Palindrome", "Same great dog, forwards and backwards."),
    B("Otto the Pittie", "Young, sturdy, ready."),
    B("Motto Otto", "His motto: more Otto."),
    B("Ot-Toe Beans", "Yes, he has them. Yes, they're perfect."),
  ],
  paco: [
    B("Paco Taco", "Tuesday's biggest fan."),
    B("Paco Picasso", "Every nap is a masterpiece."),
    B("Pac-Man Paco", "Wocka wocka wocka. Bowl empty."),
    B("Paco the Terrier", "Small package, grande heart."),
    B("Paco Loco", "The fun kind of loco."),
    B("Pacs", "The friendly abbreviation."),
    B("Paco Flamenco", "Heels click. Tail keeps time."),
  ],
  pastrami: [
    B("Pastrami on Rye", "Deli fresh, extra mustard energy."),
    B("Pastrami Salami", "The full charcuterie of charm."),
    B("Strami", "The lean cut."),
    B("Pastrami the Terrier", "Best sandwich at the counter."),
    B("Hot Pastrami", "Served warm, always."),
    B("Miss Pastrami", "Deli royalty, no crown needed."),
    B("Deli Slice Pastrami", "Fresh off the counter of good dogs."),
  ],
  patrick: [
    B("Patrick Star", "Is mayonnaise an instrument? He hopes."),
    B("St. Patrick", "The luckiest find of the year."),
    B("Pat-Pat", "The sound of him asking for exactly that."),
    B("Patrick the Dutchie", "Dutch Shepherd, world-class heart."),
    B("Shamrock Patrick", "Four-leaf clover with a tail."),
    B("Pádraig", "For formal occasions only."),
    B("Patty Cake Patrick", "Roll him over, mark him with a B."),
  ],
  peaches: [
    B("Peaches & Cream", "Life with her, basically."),
    B("Peach Fuzz", "Soft to the touch, sweet to the core."),
    B("Just Peachy", "How everything feels around her."),
    B("Peaches the Shepherd", "Georgia sweet, working smart."),
    B("Peach Cobbler", "Warm dessert in dog form."),
    B("Peach Pit", "The heart of the fruit. And the family."),
  ],
  peanut: [
    B("Peanut Butter", "Sticks to the roof of your heart."),
    B("Goober", "Technical term for a peanut. And for her."),
    B("Nutty Peanut", "In the best possible way."),
    B("Peanut the Bulldog", "Small name, sturdy build."),
    B("Peanut Brittle", "Sweet with a little snap of sass."),
    B("P-Nut", "The cool spelling."),
    B("Peanut Gallery", "Front-row commentary at every meal."),
  ],
  pebbles: [
    B("Pebbles Flintstone", "Yabba dabba do adopt her."),
    B("Pebble Beach", "A hole in one, every time."),
    B("Skipping Pebbles", "Three bounces across the yard minimum."),
    B("Pebbles the Pittie", "Bedrock loyalty."),
    B("Pebbly", "The bumpy-sweet diminutive."),
    B("River Pebbles", "Smooth. Polished. Cool to the touch."),
    B("Bedrock Pebbles", "The foundation of a happy house."),
  ],
  penelope: [
    B("Penelope the Antelope", "Springs. Sproings. Repeats."),
    B("Penny", "The shiniest one in the fountain."),
    B("Penny Lane", "In her ears and in her eyes."),
    B("Penelope the Staffy", "Greek epic, St. Louis edition."),
    B("Penny Loafer", "Loafs professionally."),
    B("Nell", "The storybook short form."),
    B("Penny for Your Thoughts", "They're all about dinner."),
  ],
  pepperoni: [
    B("Pepperoni Pizza", "The topping everyone agrees on."),
    B("Pep Rally", "Gimme a P! He'll bring the rest."),
    B("Roni", "Extra slices of personality."),
    B("Pepperoni the Terrier", "Thin crust, deep heart."),
    B("Pep in His Step", "Factory installed."),
    B("Peps", "The zesty short form."),
    B("Zamboni Pepperoni", "Smooths over every bad day."),
  ],
  pinky: [
    B("Pinky Promise", "Kept, every single time."),
    B("Pink Lemonade", "Sweet, a little tart, fully refreshing."),
    B("Pinks", "Tickled, obviously."),
    B("Pinky the Staffy", "Think big. She does."),
    B("Pinky Swear", "On it: she's wonderful."),
    B("Rosy Pinky", "The optimist of the block."),
  ],
  pip: [
    B("Pip Pip Hooray", "The official cheer of tiny dogs."),
    B("Pipsqueak", "Squeaks included at no extra charge."),
    B("Pippi Longstocking", "Strongest little girl in the world."),
    B("Pip the Cattle Pup", "Great expectations, tiny paws."),
    B("Pippin", "The brave little hobbit of the litter."),
    B("Pipette", "A precise little drop of joy."),
  ],
  piper: [
    B("Pied Piper", "The whole neighborhood follows her."),
    B("Piper the Hyper", "Runs on renewable enthusiasm."),
    B("Pipes", "Sings the song of her people at 6 a.m."),
    B("Piper the Shepherd", "Leads the flock. You're the flock."),
    B("Hot Pepper Piper", "A dash of spice daily."),
    B("Windpipes Piper", "Full volume, full heart."),
  ],
  princess: [
    B("Princess Peach", "Her castle is wherever you are."),
    B("Pretty Princess", "The name came with the face."),
    B("Prin", "Casual Fridays for royalty."),
    B("Princess the Lab", "Crown made of tennis balls."),
    B("Princess and the Pea", "Feels a kibble under twelve blankets."),
    B("Prinny", "The palace pet name."),
  ],
  pupperton: [
    B("Pupperton Abbey", "Downstairs dog with upstairs manners."),
    B("Fancy Pupperton", "Pinkies up. Paws down."),
    B("Pupp", "The abbreviated aristocrat."),
    B("Pupperton the Small Lab", "Estate-sized heart, cottage-sized dog."),
    B("Puppuccino Pupperton", "Whipped cream connoisseur."),
    B("P-Town", "The whole town's favorite."),
  ],
  raisin: [
    B("Raisin the Roof", "Party of one, invitations open."),
    B("Raisinet", "Chocolate-coated personality."),
    B("Raisin Bran", "Part of your complete breakfast."),
    B("Raisin the Rottie", "Small name, mighty pup."),
    B("Sun-Dried Sweetness", "Concentrated grape greatness."),
    B("Rai-Rai", "The sunny repeat."),
    B("California Raisin", "Heard it through the grapevine: adopt her."),
  ],
  ramsey: [
    B("Chef Ramsey", "This kibble is RAW. Perfect."),
    B("Ramsey Gourmet", "Five stars. Would beg again."),
    B("Ram", "Full speed, soft landing."),
    B("Ramsey the Presa", "Big kitchen, bigger presence."),
    B("Ramsey the Dreamboat", "Zero kitchen nightmares. All dream."),
    B("Ram-Ram", "The friendly double-tap."),
    B("Ramekin Ramsey", "The chef's smallest, sweetest dish."),
  ],
  ranger: [
    B("Park Ranger", "Protects the yard. Reports to you."),
    B("Lone Ranger", "Looking for a sidekick. Hi-yo!"),
    B("Ranger Danger", "The fun kind only."),
    B("Ranger the Cattle Pup", "Junior patrol, senior heart."),
    B("Forest Ranger", "Sniffs every tree. Files reports."),
    B("Free Ranger", "Roams the yard, returns for dinner."),
  ],
  raya: [
    B("Raya Sunshine", "You are her sunshine."),
    B("Raya the Dragon", "Trusts you. That's the whole movie."),
    B("Ray-Ray", "Double the light."),
    B("Raya the Lab", "Golden retriever energy, lab edition."),
    B("Ray of Light Raya", "Solar powered."),
    B("Rae", "The minimalist glow."),
  ],
  "reese gin": [
    B("Reese's Pieces", "Sweet outside, sweeter inside."),
    B("Reese Cup", "Two great tastes: dog and hug."),
    B("Gin Rummy", "The best card in the deck."),
    B("Reese the Lab", "Smooth like peanut butter."),
    B("Reesey", "The candy-aisle diminutive."),
    B("Reese Witherpaws", "Legally blonde. Actually chocolate."),
    B("Full House Reese Gin", "The winning hand, every deal."),
  ],
  regina: [
    B("Regina Ballerina", "First position: sit. Fifth position: flop."),
    B("Reggie", "The casual Friday version."),
    B("Gina", "Short, sweet, chin scratches please."),
    B("Regina the Pittie", "Means queen. Acts approachable."),
    B("Regina Concertina", "Music in the name."),
    B("Reg", "Dependable as they come."),
    B("Regina Tambourina", "Shakes with joy. Musically."),
  ],
  remi: [
    B("Remi Do-Re-Mi", "The first three notes just happen to be Remi."),
    B("Remi Ratatouille", "Anyone can cook. He can taste-test."),
    B("Rem", "The dream you don't wake up from."),
    B("Remi the Border Collie", "Already smarter than the doorknob. And me."),
    B("Remi Tsunami", "A wave of border collie, incoming."),
    B("Remington Remi", "The Sunday-best version."),
    B("Remi the Dream", "The rhyme and the truth."),
  ],
  rhythm: [
    B("Rhythm & Blues", "Mostly rhythm. Zero blues."),
    B("Rhythm Nation", "Population: one very good boy."),
    B("Got-the-Rhythm", "Tail keeps perfect time."),
    B("Rhythm the Retriever Pup", "Fetches on the downbeat."),
    B("Drumline Rhythm", "Tail on hardwood: the concert."),
    B("Rhyth", "The syncopated short form."),
  ],
  ronda: [
    B("Help Me Ronda", "Help, help me Ronda... find a home."),
    B("Rowdy Ronda", "Undefeated in tug-of-war."),
    B("Ronda Honda", "Reliable. Great mileage. Starts every time."),
    B("Ronda the Lab", "The dependable classic."),
    B("Rotunda Ronda", "Built comfortable."),
    B("Ron-Ron", "The friendly echo."),
    B("Ronda-Voo", "Meet her at the food bowl at six."),
  ],
  rosella: [
    B("Rosella Cinderella", "Home by dinner. Every time."),
    B("Rosie Posie", "Ring around the sweetest girl."),
    B("Rosella Umbrella", "Covers the whole family."),
    B("Rosella the Terrier", "A rose with a motor."),
    B("Rosella Novella", "A short story you'll read forever."),
    B("Zella", "The jazzy back half."),
    B("Rosella A Cappella", "No instruments needed. Just the howl."),
  ],
  rosie: [
    B("Rosie the Riveter", "We can do it! 'It' being fetch."),
    B("Rosebud", "The sweetest mystery solved."),
    B("Ring-Around-Rosie", "Everyone falls down. In love."),
    B("Rosie the Boxer", "Flexes for treats."),
    B("Rosie Cheeks", "Permanently blushing. It's the joy."),
    B("Roz", "The cool-aunt version."),
    B("Rosie Toes", "Ten perfect pink landing gear."),
  ],
  ruger: [
    B("Rugrat Ruger", "Growing up adorable."),
    B("Ruger Booger", "The rhyme every kid picks first."),
    B("Rugs", "Lies flat. Ties the room together."),
    B("Ruger the Retriever", "Brings back everything but regrets."),
    B("Snug Ruger", "As a bug. In a rug."),
    B("Roo-ger", "The bouncy pronunciation."),
    B("Sugar Ruger", "Sweetens everything he touches."),
  ],
  ruth: [
    B("Baby Ruth", "Sweeter than the candy bar."),
    B("Babe Ruth", "Calls her shot: your lap."),
    B("Truth Ruth", "The whole truth: she's wonderful."),
    B("Ruth the Staffy", "The great Bambina."),
    B("Ruthie", "The bedtime-story version."),
    B("Home Run Ruth", "Clears the bases of your heart."),
  ],
  ryder: [
    B("Knight Ryder", "A shadowy flight into the world of naps."),
    B("Low Ryder", "Takes little trips, real slow."),
    B("Ryder the Glider", "Smooth over every surface."),
    B("Ryder the Cattle Dog", "Herds with style."),
    B("Easy Ryder", "Born to be mild-mannered."),
    B("Ry-Ry", "The road-trip nickname."),
    B("Ghost Ryder", "Appears silently beside the snack table."),
  ],
  sacher: [
    B("Sacher the Snacker", "Rhymes with his life's work."),
    B("Sacher Torte", "The fanciest chocolate lab dessert."),
    B("Satchmo", "What a wonderful woof."),
    B("Sacher the Lab", "Vienna's finest, St. Louis address."),
    B("Sach", "The everyday classic."),
    B("Firecracker Sacher", "Sparkles on command."),
  ],
  samson: [
    B("Samson the Strong", "Strength: legendary. Haircuts: skipped."),
    B("Sammy", "The friendly giant next door."),
    B("Sam", "Short name. Full strength."),
    B("Samson the Staffy", "Pillar of the community."),
    B("Sam-Sam", "Double strength, double sweet."),
    B("Samson & the Couch", "An epic love story."),
  ],
  scout: [
    B("Scout's Honor", "He promises to be a good boy. Kept daily."),
    B("Scout the Lookout", "Sees the mail truck three streets away."),
    B("Talent Scout", "Found you. You're hired."),
    B("Scout Finch", "The kindest kid in the story."),
    B("Camp Scout", "S'mores committee chairdog."),
    B("Scouts", "The whole troop in one dog."),
    B("Merit Badge Scout", "Earned them all."),
  ],
  shania: [
    B("Shania Mania", "That don't impress her much. You will."),
    B("Nia", "Small name for a big future."),
    B("Shania the Pup Star", "Let's go, girls."),
    B("Shania the Pittie Pup", "Still the one. Already."),
    B("Any Dog of Mine Shania", "Country certified."),
    B("Shan", "The backstage pass version."),
  ],
  shipsey: [
    B("Shipsey Ahoy", "All paws on deck."),
    B("First Mate Shipsey", "Loyal crew, tail like a flag."),
    B("Ship-Ship", "The gentlest little tugboat."),
    B("Shipsey the Collie Pup", "Lassie's intern."),
    B("Friend-Ship", "The best kind."),
    B("Shipshape Shipsey", "Everything in order. Except the toys."),
  ],
  simba: [
    B("Simba the Lionheart", "Remember who you are: a good boy."),
    B("Hakuna Matata", "It means no worries. He means it."),
    B("Sim", "The circle of life starts at the food bowl."),
    B("Simba the Terrier", "Pride of the whole block."),
    B("Sunrise Simba", "Hold him up. Cue the music."),
    B("Simbs", "The casual royal."),
  ],
  snickers: [
    B("Snickerdoodle", "Cookie name, candy heart."),
    B("Snickers Bar", "Not himself when hungry. Relatable."),
    B("Snick", "The satisfying kind."),
    B("Snickers the Cur", "Black Mouth Cur, gold-standard heart."),
    B("Snickering Snickers", "Laughs at his own jokes. They're good."),
    B("Snickle", "The giggle made canine."),
    B("Caramel Snickers", "The gooey center is love."),
  ],
  spaceman: [
    B("Major Tom", "Ground control: we found him."),
    B("Rocket Man", "Burning out his fuse chasing a ball."),
    B("Space Cadet", "Head in the stars, paws on your lap."),
    B("Moonwalker", "Smooth criminal at the treat jar."),
    B("Lil Astronaut", "Small step for dog, giant leap for family."),
    B("Starman Spaceman", "Waiting in the yard."),
  ],
  speedy: [
    B("Speedy Zoomzalez", "Ándale! Ándale! To the couch!"),
    B("Speed Bump", "Lies down exactly where you walk."),
    B("Speedy the Shepherd", "Herds at highway speed."),
    B("Full Speedy Ahead", "The only setting."),
    B("Speedometer", "Reads: very fast, then asleep."),
    B("Speeds", "All of them, at once."),
  ],
  stella: [
    B("Stellaaaa!", "Yell it from the porch. She's coming."),
    B("Stellar Stella", "Five stars. Would pet again."),
    B("Interstellar", "Love transcends space and time."),
    B("Stella the Retriever", "Fetches like it's her constellation."),
    B("Stella Luna", "The storybook bat. Minus the bat."),
    B("Stell", "The bright short form."),
    B("Stella by Starlight", "The jazz standard of good girls."),
  ],
  stormy: [
    B("Stormy Weather", "Ninety percent chance of cuddles."),
    B("Rainbow After Stormy", "The good part was always coming."),
    B("Storm Cloud", "Rains kisses."),
    B("Stormy the Dobie", "Sleek as lightning, calm as after."),
    B("Thunderpaws", "You'll hear her joy coming."),
    B("Storms", "Weathered together, always."),
  ],
  "sweet tart": [
    B("Sweet Tart Sweetheart", "The candy aisle's finest."),
    B("Tart with a Heart", "Sour face, sugar soul."),
    B("Sweets", "The whole candy store."),
    B("Sweet Tart the Staffy", "Big candy energy."),
    B("Sugar Rush", "Side effect of one cuddle."),
    B("Candy Heart", "Reads: ADOPT ME."),
  ],
  sweetie: [
    B("Sweetie Pie", "Fresh from the oven, always warm."),
    B("Sweet Pea", "Garden variety perfect."),
    B("Sweetie Petitey", "Small, sweet, complete."),
    B("Sweetie the Beagle", "The nose knows kindness."),
    B("Sweetheart of the Deal", "Best one you'll ever make."),
    B("Tweetie Sweetie", "Sings at the window."),
    B("Sweetie Confetti", "Every day's a little parade."),
  ],
  tango: [
    B("Tango the Mango", "Tropical, sweet, a little wild."),
    B("Tango Fandango", "Two left feet, one great heart."),
    B("Two-to-Tango", "You bring the other half."),
    B("Tango the Boxer", "Fancy footwork champion."),
    B("Last Tango in St. Louis", "Spoiler: he stays."),
    B("Tang", "The zesty short form."),
  ],
  tank: [
    B("Tank You Very Much", "The politest heavyweight."),
    B("Think Tank", "Full of big ideas. Mostly about lunch."),
    B("Cuddle Tank", "Armored on the outside, mush inside."),
    B("Tank the Pittie", "Built solid, wired soft."),
    B("Tank of Hugs", "Fully loaded. Always."),
    B("Tanks a Lot", "For everything, buddy."),
  ],
  teeter: [
    B("Teeter Totter", "Up, down, and straight into your heart."),
    B("Teeter Tot", "Golden, crispy, keeper."),
    B("Tee-Tee", "Playground rules: she goes first."),
    B("Teeter the Dutchie", "Balanced. Mostly."),
    B("Seesaw Teeter", "The playground's MVP."),
    B("Wobbles", "The seesaw walk of pure joy."),
    B("Balance Beam Teeter", "Perfect ten. Every dismount."),
  ],
  thomas: [
    B("Thomas the Train", "All aboard. Next stop: home."),
    B("Tom-Tom", "The beat the whole house moves to."),
    B("Tom Terrific", "The name says it. He proves it."),
    B("Thomas the Pittie", "A really useful good boy."),
    B("Full Steam Thomas", "One speed: enthusiastic."),
    B("Choo-Choo Thomas", "Hear the tail on the floor? All aboard."),
  ],
  tippi: [
    B("Tippi Toes", "A Great Dane who thinks she's ballet-sized."),
    B("Tip-Top Tippi", "Highest point in the room, always."),
    B("Tippi Canoe", "And a couch spot too."),
    B("Tippi the Great Dane", "Great by name, greater by nature."),
    B("Tipping Point Tippi", "One look and you're done for."),
    B("Tips", "Gratuity: belly rubs."),
  ],
  tiramisu: [
    B("Tiny Tiramisu", "The fanciest dessert on four legs."),
    B("Ladyfinger", "The essential ingredient."),
    B("Misu", "Half the name, all the sweet."),
    B("Tiramisu the Rat Terrier", "Espresso-shot energy."),
    B("Pick-Me-Up Tiramisu", "That's what the word means. She delivers."),
    B("Tira", "The first taste of the good stuff."),
    B("Espresso Tiramisu", "The caffeinated layer."),
  ],
  "toasted ravioli": [
    B("T-Rav", "St. Louis knows. St. Louis approves."),
    B("The St. Louis Special", "Born crispy, served with love."),
    B("Toasty", "Warm on every side."),
    B("Rav", "The insider's order."),
    B("Extra Marinara", "For dipping. He supervises."),
    B("Golden Toasted", "Just like the recipe says."),
  ],
  tolkien: [
    B("Tolkien of the Rings", "One dog to rule the yard."),
    B("Tolkien the Wise", "Not all who wander are lost. He is, though."),
    B("Tolk", "Speak friend, and enter."),
    B("Tolkien the Shepherd", "Guards the Shire. Your Shire."),
    B("Middle-earth Tolkien", "Second breakfast advocate."),
    B("Tolks", "The fellowship's favorite."),
    B("Tolkien Walkin'", "These paws were made for it."),
  ],
  tommy: [
    B("Tommy Boy", "Holy schnikes, what a dog."),
    B("Polar Bear Tommy", "The Great White Pyrenees."),
    B("Tommy Two-Tons", "Weight measured in love units."),
    B("Tommy the Pyrenees", "A mountain that comes when called. Sometimes."),
    B("Gentle Giant Tommy", "The mountain comes to you."),
    B("Toms", "The plural of gentle."),
  ],
  tony: [
    B("Tony the Tiger", "Thinks breakfast is grrreat."),
    B("Tony Pepperoni", "The classic rhyme, the classic boy."),
    B("T-Bone Tony", "Prime cut."),
    B("Tony the Lab Pup", "Fresh talent, big future."),
    B("Tony Baloney", "Full of it. The good kind."),
    B("Ton-Ton", "Small now. Give him a minute."),
  ],
  triton: [
    B("Triton the Titan", "Mythologically good boy."),
    B("Triton of the Sea", "Rules puddles with an iron paw."),
    B("Sea-Dog Triton", "Land ho! And also, dinner ho!"),
    B("Triton the Pittie", "Neptune's favorite."),
    B("Triton Neptune", "Second in command of the sea. First in the yard."),
    B("Try Triton", "You'll keep him."),
    B("Triton High Tide", "Joy comes in waves."),
  ],
  tunnel: [
    B("Tunnel of Love", "The light at the end is him."),
    B("Tunnel Vision", "Locked on: you."),
    B("Carpool Tunnel", "Best seat in the car."),
    B("Tunnel the Lab Pup", "Digs his way into everything."),
    B("Wind Tunnel", "The zoomies have aerodynamics."),
    B("Tunn", "The shortcut."),
  ],
  tyler: [
    B("Tyler the Cuddler", "Creates masterpieces of napping."),
    B("Totally Tyler", "One hundred percent of the time."),
    B("Ty", "The knot that holds it together."),
    B("Tyler the Pittie", "Senior statesman of snuggles."),
    B("Ty-Dye", "Colors every day brighter."),
    B("Old Tyler Faithful", "Erupts with joy on schedule."),
  ],
  tyson: [
    B("Tyson the Bison", "Built like a legend, gentle like a lamb."),
    B("Sonny", "Every day's forecast."),
    B("Nuggets", "The premium brand."),
    B("Tyson the Gentle", "The senior with the softest lean."),
    B("Ty-Son", "Somebody's boy. Could be yours."),
    B("Sonny Side Up", "How he wakes up. Always."),
  ],
  uhtred: [
    B("Uhtred of the Backyard", "Destiny is all. Dinner is most."),
    B("Uht-Oh", "The sound before the zoomies."),
    B("Uhtred the Bold", "Claims every couch for the kingdom."),
    B("Uhtred the Staffy", "Warrior poet, mostly poet."),
    B("Uhtred Son of Uhtred", "The full saga."),
    B("Treddy", "The mead-hall pet name."),
  ],
  uno: [
    B("Numero Uno", "First in line, first in heart."),
    B("Wild Card Uno", "Changes the whole game."),
    B("Uno Momento", "All she needs to win you over."),
    B("Uno the Cattle Pup", "Draw two: her and a friend."),
    B("Reverse Card Uno", "Now YOU chase HER."),
    B("Ones", "The whole hand."),
  ],
  vida: [
    B("Viva la Vida", "Long live the good girl."),
    B("Feisty Vida", "A Feist being feisty. Poetry."),
    B("Vee", "Short for victory."),
    B("Vida the Feist", "Rare breed, common decency."),
    B("Vida Loca", "Livin' it, gently."),
    B("Veeds", "The backyard call sign."),
    B("Vida the Good Life", "It's what her name means. Accurate."),
  ],
  violet: [
    B("Violet the Pilot", "Cleared for takeoff. And naps."),
    B("Ultra Violet", "Beyond visible sweetness."),
    B("Sweet Violet", "Picked fresh."),
    B("Violet the Cattle Pup", "Purple heart, blue collar."),
    B("Vi", "The tiny bloom."),
    B("Violet Bouquet", "A whole armful of good."),
  ],
  walker: [
    B("Walker Texas Basset", "Justice moves at basset speed."),
    B("Walkies", "His name IS the magic word."),
    B("Jay Walker", "Crosses wherever the smells are."),
    B("Walker the Basset", "Low rider, long ears, no worries."),
    B("Slow Walker", "Basset speed is a lifestyle."),
    B("Walk", "The whole name is an invitation."),
    B("Sleepwalker", "Naps in motion."),
  ],
  watson: [
    B("Dear Watson", "Elementary: she's wonderful."),
    B("Watts Up", "Fully charged."),
    B("Watts", "Powers the whole house."),
    B("Watson the Pittie", "Solves the case of the missing treat. She ate it."),
    B("Sherlock's Better Half", "The brains of the operation."),
    B("Watson the Wagson", "The tail solves everything."),
    B("Watson On the Case", "The case of the missing treat. Solved."),
  ],
  weston: [
    B("Weston the Best-One", "The rhyme checks out."),
    B("Wild Wild Weston", "The friendliest outlaw."),
    B("Wes", "Direct. Efficient. Wiggly."),
    B("Weston the Boxer", "Undefeated in cuddling."),
    B("Go West Weston", "Best direction: toward him."),
    B("Wessy", "The bedtime version."),
  ],
  wiley: [
    B("Wiley Coyote", "Genius plans. Adorable results."),
    B("Beep-Beep Wiley", "Catches the roadrunner in his dreams."),
    B("Wiles", "Uses them all on you."),
    B("Wiley the Small Lab", "ACME-certified good boy."),
    B("Wile E. Heart", "The trap was love all along."),
    B("Why-Ley", "Because he's perfect, that's why."),
  ],
  wilma: [
    B("Wilma Whirlwind", "Sweeps through. Leaves joy."),
    B("Wilhelmina", "For formal occasions and vet visits."),
    B("Wilms", "The cozy short version."),
    B("Wilma the Pittie", "Bedrock's finest, relocated."),
    B("Wilma Welcome", "The greeting committee of one."),
    B("Willy-Nilly Wilma", "Zoomies have no schedule."),
  ],
  winnie: [
    B("Winnie the Pooch", "Oh bother. Out of treats again."),
    B("Win-Win", "Everybody's best-case scenario."),
    B("Winner Winner", "Chicken dinner enthusiast."),
    B("Winnie Bear", "Hunny jar sold separately."),
    B("Windy City Winnie", "Blows in, hearts follow."),
    B("Winn", "The single-syllable victory."),
    B("Blue Ribbon Winnie", "First place, every category."),
  ],
  xena: [
    B("Xena the Warrior", "Battle cry: yip-yip-yiyiyiyi!"),
    B("X Marks the Spot", "The treasure is her."),
    B("Xena Hyena", "Laughs at all your jokes."),
    B("Xena the Pittie", "Legendary. Documented. Adoptable."),
    B("Xena Ballena", "A whale of a personality."),
    B("Xe", "The rarest element: a perfect dog."),
    B("Warrior Pose Xena", "Namaste. Now feed her."),
  ],
  zeke: [
    B("Zeke the Sneak", "Treats vanish. No witnesses."),
    B("Ezekiel", "The full Sunday name."),
    B("Squeaky Zeke", "His toys sing his song."),
    B("Zeke the Bulldog", "Sturdy frame, softer soul."),
    B("Zeke Unique", "One of one, rhyme included."),
    B("Zekey", "The bedtime call."),
    B("Bulldozeke", "Gently flattens all resistance."),
  ],
  zeus: [
    B("Zeus on the Loose", "Thunder in the yard."),
    B("Zeus the Moose", "Husky outside, moose energy inside."),
    B("Thunderbolt Zeus", "Strikes cuddles without warning."),
    B("Zeus the Husky", "Olympus called. He stayed for dinner."),
    B("Zeusy", "The god of small snuggles."),
    B("Mount Olympus Zeus", "The peak of good boys."),
    B("Zeus Juice", "One hundred percent concentrated joy."),
  ],
  zuse: [
    B("Zuse the Caboose", "Always last to leave the food bowl."),
    B("Zuzu", "Every time a bell rings, he wants dinner."),
    B("Zuse Cruise", "Smooth sailing, big lab smile."),
    B("Zuse the Lab", "The friendly engine of the house. Er, heart."),
    B("Papa Zuse", "Steady as they come."),
    B("Zu", "Short. Zen. Zuse."),
  ],

  // ── Common names not on today's listings — the visitor maker meets these
  // dogs every day, so they get the same hand-written care. ──
  max: [
    B("Max to the Max", "There is no half speed."),
    B("Maximus", "The gladiator of nap time."),
    B("Mad Max", "Fury Road? More like Furry Road."),
  ],
  charlie: [
    B("Good Ol' Charlie", "A classic for a reason."),
    B("Charlie Brown", "Good grief, what a good dog."),
    B("Char-Char", "Twice as toasty."),
  ],
  daisy: [
    B("Upsy-Daisy", "The bounce-back champion."),
    B("Crazy Daisy", "Certified silly."),
    B("Daisy Chain", "Links the whole family together."),
  ],
  rocky: [
    B("Rocky Road", "Sweet, a little nutty."),
    B("Rock Solid Rocky", "Dependable since round one."),
    B("Yo Rocky", "Went the distance."),
  ],
  coco: [
    B("Hot Coco", "Best enjoyed on cold mornings."),
    B("Coco Puff", "Cuckoo for cuddles."),
    B("Coco Loco", "Runs on zoomies and vibes."),
  ],
  duke: [
    B("Duke Box", "Plays all the hits."),
    B("Dukey", "The friendly neighborhood classic."),
    B("Duke of Naps", "His duchy: the couch."),
  ],
  bear: [
    B("Bear Hug", "His specialty. No escape. No complaints."),
    B("Teddy Bear", "Life size."),
    B("Grizzly Bear", "Fierce about breakfast only."),
  ],
  milo: [
    B("Milo the Explorer", "Adventures start at the door."),
    B("My-lo", "Emphasis on MY."),
    B("Milo High Club", "Frequent flyer of the couch leap."),
  ],
  sadie: [
    B("Sadie Lady", "Elegance with a tennis ball."),
    B("Sweet Sadie", "The neighborhood agrees."),
    B("Say-Say", "Says it all with her eyes."),
  ],
  molly: [
    B("Good Golly Miss Molly", "Sure loves the ball."),
    B("Lolly Molly", "Sweetness on a stick."),
    B("Mols", "The cozy version."),
  ],
  cooper: [
    B("Cooper the Trooper", "Through rain, mud, and bath time."),
    B("Chicken Coop", "Where all the tenders go."),
    B("Coop", "There he is."),
  ],
  rex: [
    B("T-Rex", "Tiny arms not included."),
    B("Rexy", "The friendly kind of dinosaur energy."),
    B("Rex Effects", "Special, obviously."),
  ],
  bruno: [
    B("We Don't Talk About Bruno", "But we can't stop, either."),
    B("Bruno Mars", "Out of this world."),
    B("Bru", "The strong quiet type."),
  ],
  ollie: [
    B("Ollie-Oop", "Catches everything you throw."),
    B("Ollie Trolley", "Rolls through town collecting friends."),
    B("Ol' Ollie", "New dog, timeless heart."),
  ],
  biscuit: [
    B("Biscuits and Gravy", "The full southern breakfast of dogs."),
    B("Butter Biscuit", "Flaky outside, warm inside."),
    B("Bisky", "Fresh from the oven of good dogs."),
  ],
  ziggy: [
    B("Ziggy Stardust", "Played it left hand, fetched it right."),
    B("Zigzag Ziggy", "Never walks a straight line. Why would he?"),
    B("Zigs", "The move and the dog."),
  ],
  penny: [
    B("Lucky Penny Girl", "Heads up, every time."),
    B("Penny Whistler", "The happiest sound in the house."),
    B("Pen-Pen", "Twice the shine."),
  ],
  toby: [
    B("Toby or Not Toby", "That is never the question."),
    B("Tobes", "The cozy classic."),
    B("Toblerone", "The fancy chocolate of good boys."),
  ],
  winston: [
    B("Winston Furchill", "Never, never, never give up the couch."),
    B("Win", "What everyone did when he arrived."),
    B("Winnie the Winston", "The formal teddy bear."),
  ],
  murphy: [
    B("Murphy's Law", "Anything that can be licked, will be licked."),
    B("Murph", "The one-syllable good boy."),
    B("Murphy Bed", "Folds out anywhere."),
  ],
  tucker: [
    B("Tucker the Trucker", "Long hauls to the mailbox."),
    B("Tuck", "Goodnight move and nickname in one."),
    B("Tuckered Out Tucker", "His name is a bedtime story."),
  ],
  gus: [
    B("Gus-Gus the Great", "Cinderella's favorite, everyone's favorite."),
    B("Gustopher", "The long form for fancy dinners."),
    B("Gusto", "How he does everything."),
  ],
  oreo: [
    B("Double-Stuf Oreo", "Extra filling, extra love."),
    B("Oreo Milkshake", "Best thing to happen to a couch."),
    B("Twist-and-Lick Oreo", "He knows the routine."),
  ],
  shadow: [
    B("Shadow the Velcro", "Wherever you go, there he is."),
    B("Me and My Shadow", "The full song, daily."),
    B("Shadow Puppet", "The cutest thing on any wall."),
  ],
  ginger: [
    B("Gingersnap", "Sweet with a little sass."),
    B("Ginger Ale", "Bubbly and good for you."),
    B("Gingerbread", "Can't catch her either."),
  ],
  pepper: [
    B("Pep Talk Pepper", "The team huddle happens at her bowl."),
    B("Pepper Jack", "A little spicy, very cheesy."),
    B("Peppercorn", "Small, mighty, seasons everything."),
  ],
  oscar: [
    B("Award Season Oscar", "And the good boy goes to..."),
    B("Oscar Winner", "Best performance by a good boy."),
    B("Ozzy Oscar", "The backyard rock tour."),
  ],
  hank: [
    B("Honky-Tonk Hank", "Two-steps to the food bowl."),
    B("Hank the Hugger", "So lonesome he could hug. So he does."),
    B("Hanky", "The comfort object himself."),
  ],
  ruby: [
    B("Ruby Tuesday", "And every other day too."),
    B("Ruby Slippers", "There's no place like her home. Yours."),
    B("Rubes", "The gem, casually."),
  ],
  finn: [
    B("Finn-tastic", "The pun his name demanded."),
    B("Dorsal Finn", "Cuts through the yard like open water."),
    B("Finny", "Swims through life."),
  ],
};

// ── Per-dog override decks ─────────────────────────────────────────────
//
// When two listed dogs share a name, they must NOT share nicknames — a
// family should never see the same card on two different dogs. The first
// dog keeps the Name Book entry; the second gets its own complete seven,
// written for that specific dog, keyed by its RescueGroups listing id.
export const DECK_OVERRIDES: Record<string, BookCard[]> = {
  // BELLA — American Bulldog, adult (the amstaff Bella keeps the book).
  "22627788": [
    B("Taco Bella", "Thinks outside the bun."),
    B("Ciao Bella", "Hello AND goodbye kisses."),
    B("Jingle Bella", "You can hear the happy from the driveway."),
    B("Bella Fresca", "Cool, sweet, refreshing."),
    B("Bella the Bulldog", "Says what she is. Is what she says."),
    B("Bulldozer Bella", "Flattens hearts, gently."),
    B("Bella Vista", "The best view in the house."),
  ],
  // DIESEL — Pit Bull Terrier, senior (the wolfhound Diesel keeps the book).
  "22627276": [
    B("Diesel Truck", "Classic model. Runs on love."),
    B("Big Rig Diesel", "Long-haul snuggler."),
    B("Grandpa Diesel", "Seen it all. Naps through most of it."),
    B("Old School Diesel", "They don't make them like this anymore."),
    B("Diesel Power", "Torque measured in tail wags."),
    B("Gentle Diesel", "The rumble is loud. The heart is soft."),
    B("Dee-Dee", "The family shorthand."),
  ],
  // JASPER — breed unknown (the chihuahua Jasper keeps the book).
  "22647258": [
    B("Jasper the Gem", "It's a real gemstone. He's the real deal."),
    B("Jazz Paws", "Every step's a little showtune."),
    B("Jasper Whisper", "The quietest good boy."),
    B("Jazz Man Jasper", "Smooth. Improvises snack time."),
    B("Jazz-Jazz", "Double time."),
    B("Gem-Gem", "Twice as precious."),
    B("Smooth Jazz Jasper", "Late-night radio voice, daytime tail."),
  ],
  // PENELOPE — Carolina Dog, young (the amstaff Penelope keeps the book).
  "22223788": [
    B("Copper Penny", "Carolina gold, actually."),
    B("Lucky Penny", "Found on heads. Keep her forever."),
    B("Nellie", "The old-fashioned sweetheart cut of Penelope."),
    B("Penelope Envelope", "First-class delivery of kisses."),
    B("Penny Whistle", "The happiest sound in the house."),
    B("Pretty Penny", "Worth every bit."),
    B("Pen Pal Penelope", "Writes back with her tail."),
  ],
  // PIPER — Australian Cattle Dog mix (the shepherd Piper keeps the book).
  "22656836": [
    B("Sandpiper", "Tiny bird energy, beach-day heart."),
    B("Peter Piper", "Picked a peck of perfect pets."),
    B("Bagpipes", "Loud, proud, oddly beautiful."),
    B("Piper Cub", "Small plane. Big sky."),
    B("Pepper Piper", "A little spicy, a lot sweet."),
    B("Pi", "Irrational love, infinite digits."),
    B("Piper the Heeler", "Heals hearts, heels sometimes."),
  ],
  // RAMSEY — Retriever mix, young (the Presa Ramsey keeps the book).
  "22194580": [
    B("Golden Ramsey", "The retriever special."),
    B("Ram-Jam", "Whoa, it's fetch time."),
    B("Ramsey the Retriever", "Brings it back. Brings it all back."),
    B("Ramsey Pancakes", "Flips for breakfast."),
    B("Ramble-On Ramsey", "Sings the song of the open yard."),
    B("Ramsey Whamsey", "The bounciest rhyme in the litter."),
    B("Rams", "Short. Sturdy. Sweet."),
  ],
  // SCOUT — Australian Cattle Dog, baby (the young Scout keeps the book).
  "22656831": [
    B("Cub Scout", "Earning his snuggle badges."),
    B("Cookie Scout", "Sales record: every heart in the room."),
    B("Scooter", "Zoom-zoom, puppy edition."),
    B("Scout the Sprout", "Growing in every direction."),
    B("Trail Scout", "First one down every path."),
    B("Den Leader's Favorite", "Unofficial. Universal."),
    B("Eagle Scout Someday", "The training montage is adorable."),
  ],
  // TANK — Rottweiler, adult (the pit-mix Tank keeps the book).
  "22611930": [
    B("Tank Top", "Summer's finest look."),
    B("Fish Tank", "Full of bubbles, zero fish."),
    B("Tiny Tank", "He believes it. Let him."),
    B("Gentle Tank", "Heavy armor, marshmallow center."),
    B("Tank the Rottie", "Exactly what it says on the label."),
    B("Tanky", "The cuddly diminutive."),
    B("Rumble Tank", "That's just his happy noise."),
  ],
};
